### PR TITLE
🐛 Fix APIExport virtual workspace API bug

### LINKED ISSUE #2501: flake: TestDeploymentCoordinator
### Describe the bug

```
2022-12-15T15:11:39.0852488Z --- FAIL: TestDeploymentCoordinator (70.09s)
2022-12-15T15:11:39.0855832Z     kcp.go:127: shared kcp server will target configuration "/home/runner/work/kcp/kcp/.kcp/admin.kubeconfig"
2022-12-15T15:11:39.0859071Z     workspaces.go:196: Created organization workspace root:e2e-org-znfgz
2022-12-15T15:11:39.0863338Z     workspaces.go:126: Created root:universal workspace root:e2e-org-znfgz:synctargets
2022-12-15T15:11:39.0866448Z     workspaces.go:126: Created root:universal workspace root:e2e-org-znfgz:workload-1
2022-12-15T15:11:39.0871331Z     workspaces.go:126: Created root:universal workspace root:e2e-org-znfgz:workload-2
2022-12-15T15:11:39.0873940Z     util.go:112: Saving test artifacts for test "TestDeploymentCoordinator" under "/tmp/e2e/TestDeploymentCoordinator/3181476435".
2022-12-15T15:11:39.0879096Z     syncer.go:141: Configuring workspace root:e2e-org-znfgz:synctargets for syncing
2022-12-15T15:11:39.0886386Z     kubectl.go:59: running: KUBECONFIG=/tmp/e2e/TestDeploymentCoordinator/3181476435/artifacts/root_e2e-org-znfgz_synctargets.kubeconfig kubectl kcp workload sync east --syncer-image=kind.local/syncer-c2e3073d5026a8f7f2c47a50c16bdbec:a4d77b220ce934e4e12fb443b04f413e518272ebd263465dca7285428a404ec4 --output-file=- --qps=-1 --feature-gates=CustomResourceValidationExpressions=true --api-import-poll-interval=5s --downstream-namespace-clean-delay=2s
2022-12-15T15:11:39.0887729Z     kubectl.go:89: running: kubectl --kubeconfig /home/runner/work/kcp/kcp/.kcp/kind.kubeconfig apply -f -
2022-12-15T15:11:39.0888663Z     syncer.go:589: checking secret kcp-syncer-east-2fu92b3q/kcp-syncer-east-2fu92b3q for annotation kubernetes.io/service-account.name=kcp-syncer-east-2fu92b3q
2022-12-15T15:11:39.0889766Z     syncer.go:589: checking secret kcp-syncer-east-2fu92b3q/kcp-syncer-east-2fu92b3q-token for annotation kubernetes.io/service-account.name=kcp-syncer-east-2fu92b3q
2022-12-15T15:11:39.0890304Z     syncer.go:523: Cluster "east" is Ready
2022-12-15T15:11:39.0890860Z     syncer.go:141: Configuring workspace root:e2e-org-znfgz:synctargets for syncing
2022-12-15T15:11:39.0892748Z     kubectl.go:59: running: KUBECONFIG=/tmp/e2e/TestDeploymentCoordinator/3181476435/artifacts/root_e2e-org-znfgz_synctargets.kubeconfig kubectl kcp workload sync west --syncer-image=kind.local/syncer-c2e3073d5026a8f7f2c47a50c16bdbec:a4d77b220ce934e4e12fb443b04f413e518272ebd263465dca7285428a404ec4 --output-file=- --qps=-1 --feature-gates=CustomResourceValidationExpressions=true --api-import-poll-interval=5s --downstream-namespace-clean-delay=2s
2022-12-15T15:11:39.0893943Z     kubectl.go:89: running: kubectl --kubeconfig /home/runner/work/kcp/kcp/.kcp/kind.kubeconfig apply -f -
2022-12-15T15:11:39.0895020Z     syncer.go:589: checking secret kcp-syncer-west-2vca45dr/kcp-syncer-west-2vca45dr for annotation kubernetes.io/service-account.name=kcp-syncer-west-2vca45dr
2022-12-15T15:11:39.0896034Z     syncer.go:589: checking secret kcp-syncer-west-2vca45dr/kcp-syncer-west-2vca45dr-token for annotation kubernetes.io/service-account.name=kcp-syncer-west-2vca45dr
2022-12-15T15:11:39.0896775Z     syncer.go:523: Cluster "west" is Ready
2022-12-15T15:11:39.0898211Z     syncer.go:523: Cluster "east" is Ready
2022-12-15T15:11:39.0898651Z     syncer.go:523: Cluster "west" is Ready
2022-12-15T15:11:39.0899109Z     deployment_coordinator_test.go:114: Create 2 locations, one for each SyncTargets
2022-12-15T15:11:39.0899864Z     deployment_coordinator_test.go:118: Bind workload workspace 1 to location workspace for the east location
2022-12-15T15:11:39.0900654Z     bind.go:59: Bind workload workspace root:e2e-org-znfgz:synctargets
2022-12-15T15:11:39.0901894Z     kubectl.go:59: running: KUBECONFIG=/tmp/e2e/TestDeploymentCoordinator/3181476435/artifacts/root_e2e-org-znfgz_workload-1.kubeconfig kubectl kcp bind compute root:e2e-org-znfgz:synctargets --location-selectors=region=east
2022-12-15T15:11:39.0979765Z     deployment_coordinator_test.go:126: Bind workload workspace 2 to location workspace for the east location
2022-12-15T15:11:39.0985417Z     bind.go:59: Bind workload workspace root:e2e-org-znfgz:synctargets
2022-12-15T15:11:39.0987934Z     kubectl.go:59: running: KUBECONFIG=/tmp/e2e/TestDeploymentCoordinator/3181476435/artifacts/root_e2e-org-znfgz_workload-2.kubeconfig kubectl kcp bind compute root:e2e-org-znfgz:synctargets --location-selectors=region=east
2022-12-15T15:11:39.1009918Z     deployment_coordinator_test.go:134: Bind workload workspace 1 to location workspace for the west location
2022-12-15T15:11:39.1012365Z     bind.go:59: Bind workload workspace root:e2e-org-znfgz:synctargets
2022-12-15T15:11:39.1016632Z     kubectl.go:59: running: KUBECONFIG=/tmp/e2e/TestDeploymentCoordinator/3181476435/artifacts/root_e2e-org-znfgz_workload-1.kubeconfig kubectl kcp bind compute root:e2e-org-znfgz:synctargets --location-selectors=region=west
2022-12-15T15:11:39.1064738Z     deployment_coordinator_test.go:142: Bind workload workspace 2 to location workspace for the west location
2022-12-15T15:11:39.1065587Z     bind.go:59: Bind workload workspace root:e2e-org-znfgz:synctargets
2022-12-15T15:11:39.1066882Z     kubectl.go:59: running: KUBECONFIG=/tmp/e2e/TestDeploymentCoordinator/3181476435/artifacts/root_e2e-org-znfgz_workload-2.kubeconfig kubectl kcp bind compute root:e2e-org-znfgz:synctargets --location-selectors=region=west
2022-12-15T15:11:39.1067712Z     deployment_coordinator_test.go:150: Get the root compute APIExport Virtual Workspace URL
2022-12-15T15:11:39.1068262Z     deployment_coordinator_test.go:159: Start the Deployment controller
2022-12-15T15:11:39.1085078Z     accessory.go:76: running: /home/runner/work/kcp/kcp/bin/deployment-coordinator --kubeconfig=/home/runner/work/kcp/kcp/.kcp/admin.kubeconfig --context=base --server=https://10.1.0.83:6444/services/apiexport/root:compute/kubernetes
2022-12-15T15:11:39.1086235Z     deployment_coordinator_test.go:213: Create workload in workload workspace "root:e2e-org-znfgz:workload-1", with replicas set to 4
2022-12-15T15:11:39.1087208Z     deployment_coordinator_test.go:226: Wait for the workload in workspace "root:e2e-org-znfgz:workload-1" to be started and available with 4 replicas
2022-12-15T15:11:39.1088337Z     assertions.go:1691: Waiting for condition, but got: Deployment root:e2e-org-znfgz:workload-1/test should have been prepared for transformation by the coordinator for the east syncTarget
2022-12-15T15:11:39.1088919Z     deployment_coordinator_test.go:230: 
2022-12-15T15:11:39.1089328Z         	Error Trace:	util.go:297
2022-12-15T15:11:39.1090045Z         	            				deployment_coordinator_test.go:230
2022-12-15T15:11:39.1090974Z         	            				deployment_coordinator_test.go:261
2022-12-15T15:11:39.1091485Z         	Error:      	Condition never satisfied
2022-12-15T15:11:39.1091905Z         	Test:       	TestDeploymentCoordinator
2022-12-15T15:11:39.1092577Z         	Messages:   	deployment root:e2e-org-znfgz:workload-1/test was not synced
2022-12-15T15:11:39.1093150Z     accessory.go:68: cleanup: ending `deployment-coordinator`
```

### Steps To Reproduce

Mostly reproducible in some github actions

### Expected Behaviour

Test should not flake

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ncdc**
## Summary
Fix bug in the APIExport virtual workspace where the APIDefinitionSet was sometimes calculated incorrectly. When an APIResourceSchema informer event came in, we were supposed to enqueue all APIExports in the same logical cluster, but instead it was accidentally trying to enqueue the APIResourceSchema itself.

## Related issue(s)

Fixes #2501

### CODE REVIEW

**Review by stevekuznetsov — APPROVED** [review]

File: pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go [hunk 1]
```diff
@@ -154,13 +158,13 @@ func (c *APIReconciler) enqueueAPIResourceSchema(obj interface{}, logger logr.Lo
...
 	if len(exports) == 0 {
-		logger.V(2).Info("No kubernetes APIExport found for APIResourceSchema")
+		logger.V(2).Info("No APIExports found")
 		return
 	}
 
 	for _, export := range exports {
 		logger.WithValues("apiexport", export.Name).V(2).Info("Queueing APIExport for APIResourceSchema")
-		c.enqueueAPIExport(obj, logger.WithValues("reason", "APIResourceSchema change", "apiResourceSchema", name))
+		c.enqueueAPIExport(export, logger.WithValues("reason", "APIResourceSchema change", "apiResourceSchema", name))
```
Comment (sttts) [inline pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go:167]: ✨

Comment (vincepri) [reply pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go:167]: Could the input to enqueueAPIExport be typed maybe?

Comment (ncdc) [reply pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go:167]: That could be a good thing too 😄
