### PR TITLE
:bug: Decouple internal and external logical-cluster-admin access

### LINKED ISSUE #2872: bug: logical cluster admin can't access both internal/external endpoints
### Describe the bug

Currently the logical cluster admin kubeconfig is used to access both the [external front-proxy endpoint](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/tenancy/workspace/workspace_controller.go#L194..L195), and also the [shard directly via the baseURL](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/tenancy/workspace/workspace_reconcile.go#L71..L72) - this won't work in the case where different CA certs are used for shard and front-proxy (such as in the [helm-charts](https://github.com/kcp-dev/helm-charts))

This only works in CI because we use the same serving-ca.crt for both shard and front-proxy, which is Ok for development but probably not a common choice for production deployments.

### Steps To Reproduce

1. Deploy KCP in a configuration where different CA certs are used for shard and front-proxy (such as in the [helm-charts](https://github.com/kcp-dev/helm-charts))
2. Create a workspace
3. Note that the workspace is stuck `Initializing`

The logs show that the single CA from the logical-cluster-admin kubeconfig can't access both endpoints for the two phases of scheduling (thanks to @sttts for the help figuring this out):

1. The creation of the logical cluster object. At this point the shard name hash is known (an annotation on the Workspace). We cannot go through the proxy because it does not know about the logical cluster yet.
2. the initialization phase. At this point the logical cluster exists and every access is like any other workspace access. I.e. it should go through the proxy.

### Expected Behaviour

The two phases of scheduling should complete successfully.

### Additional Context

[Discussion on slack](https://kubernetes.slack.com/archives/C021U8WSAFK/p1678103495741019)

tl;dr we agreed to add a `--external-logical-cluster-admin-kubeconfig` similar to the previous (reverted) change [adding an external admin kubeconfig](https://github.com/kcp-dev/kcp/commit/339a071a6b3fb2d4e9d3f6d72e900183a8885ca0), but limited to the permissions needed for workspace scheduling and deletion.

### PR DESCRIPTION
**Pull request by hardys**
## Summary
Currently the logical cluster admin kubeconfig is used to access both the [external front-proxy endpoint](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/tenancy/workspace/workspace_controller.go#L194..L195), and also the [shard directly via the baseURL](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/tenancy/workspace/workspace_reconcile.go#L71..L72) - this won't work in the case where different CA certs are used for shard and front-proxy (such as in the [helm-charts](https://github.com/kcp-dev/helm-charts))

This only works in CI because we use the same serving-ca.crt for both shard and front-proxy, (in a future PR I will propose a change which better reflects the likely scenario in production deployments).

Fixes #2872

### CODE REVIEW

File: cmd/sharded-test-server/virtual.go [hunk 1]
```diff
@@ -88,9 +88,9 @@ func newVirtualWorkspace(ctx context.Context, index int, servingCA *crypto.CA, h
 		return nil, fmt.Errorf("failed to create vw client cert: %w", err)
 	}
 
-	servingCAPath, err := filepath.Abs(filepath.Join(workDirPath, ".kcp/serving-ca.crt"))
+	servingCAPath, err := filepath.Abs(filepath.Join(workDirPath, ".kcp/shard-serving-ca.crt"))
 	if err != nil {
-		return nil, fmt.Errorf("error getting absolute path for %q: %w", filepath.Join(workDirPath, ".kcp/serving-ca.crt"), err)
+		return nil, fmt.Errorf("error getting absolute path for %q: %w", filepath.Join(workDirPath, ".kcp/shard-serving-ca.crt"), err)
```
[the remark this answers is not in the document]
Comment (hardys) [reply cmd/sharded-test-server/virtual.go:93]: I was unclear about that - indeed the e2e tests are failing because `admin.kubeconfig` can't connect to the VW servers directly when the CA certs are decoupled - do we expect users to connect directly to the VW server endpoints, or only via the proxy?

[the remark this answers is not in the document]
Comment (sttts) [reply cmd/sharded-test-server/virtual.go:93]: They connect directly. There could potentially be a proxy in between. But the paths used for different services must be non-overlapping.

[the remark this answers is not in the document]
Comment (hardys) [reply cmd/sharded-test-server/virtual.go]: I removed the splitting of CA certs for now, will revisit as a follow-up

**Comment by hardys** [comment]
/retitle :bug: Decouple internal and external logical-cluster-admin access

File: cmd/sharded-test-server/frontproxy.go [hunk 2]
```diff
@@ -312,7 +312,7 @@ func writeShardKubeConfig(workDirPath string) error {
 }
 
 func writeLogicalClusterAdminKubeConfig(hostIP, workDirPath string) error {
-	baseHost := fmt.Sprintf("https://%s", net.JoinHostPort(hostIP, "6443"))
+	baseHost := fmt.Sprintf("https://%s", net.JoinHostPort(hostIP, "6444"))
```
[the remark this answers is not in the document]
Comment (sttts) [reply cmd/sharded-test-server/frontproxy.go:315]: ack

File: pkg/reconciler/tenancy/workspace/workspace_controller.go [hunk 3]
```diff
@@ -119,13 +118,12 @@ type workspaceResource = committer.Resource[*tenancyv1alpha1.WorkspaceSpec, *ten
 type Controller struct {
 	queue workqueue.RateLimitingInterface
 
-	shardName                 string
-	shardExternalURL          func() string
```
Comment (sttts) [inline pkg/reconciler/tenancy/workspace/workspace_controller.go:123]: do you understand why this closure can be removed? I remember that this was about early plumbing but late computation of the value, maybe about shard object creation.

File: pkg/server/options/options.go [hunk 4]
```diff
@@ -167,6 +167,7 @@ func (o *Options) AddFlags(fss *cliflag.NamedFlagSets) {
 	fs.StringVar(&o.Extra.ShardClientCertFile, "shard-client-cert-file", o.Extra.ShardClientCertFile, "Path to a client certificate file the shard uses to communicate with other system components.")
 	fs.StringVar(&o.Extra.ShardClientKeyFile, "shard-client-key-file", o.Extra.ShardClientKeyFile, "Path to a client certificate key file the shard uses to communicate with other system components.")
 	fs.StringVar(&o.Extra.LogicalClusterAdminKubeconfig, "logical-cluster-admin-kubeconfig", o.Extra.LogicalClusterAdminKubeconfig, "Kubeconfig holding admin(!) credentials to other shards. Defaults to the loopback client")
+	fs.StringVar(&o.Extra.ExternalLogicalClusterAdminKubeconfig, "external-logical-cluster-admin-kubeconfig", o.Extra.ExternalLogicalClusterAdminKubeconfig, "Kubeconfig holding admin(!) credentials talking to the external address (e.g. the front-proxy). Defaults to the loopback client")
```
[the remark this answers is not in the document]
Comment (hardys) [reply pkg/server/options/options.go:170]: Yes - it's a copy paste from the existing flag, shall I update both here?

File: pkg/reconciler/tenancy/workspace/workspace_controller.go (hunk 3 above)
Comment (hardys) [reply pkg/reconciler/tenancy/workspace/workspace_controller.go:123]: It can be removed because instead of explicitly setting shardExternalURL in the client, we rely on the server set in the `externalLogicalClusterAdminConfig` (see `workspace_reconcile.go` below) - AFAICS this was only required before so the endpoint from `logicalClusterAdminConfig` could overridden?

Comment (ncdc) [reply pkg/reconciler/tenancy/workspace/workspace_controller.go:123]: Haven't reviewed this PR, but the closure was required before because at the time the controller is created, the shard external URL isn't necessarily set/correct.

File: pkg/server/options/options.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (sttts) [reply pkg/server/options/options.go:170]: yes

File: pkg/reconciler/tenancy/workspace/workspace_controller.go (hunk 3 above)
Comment (hardys) [reply pkg/reconciler/tenancy/workspace/workspace_controller.go:123]: Thanks for clarifying @ncdc - yes AFAICS it's so we can (default to genericspiserver.ExternalAddress)[https://github.com/kcp-dev/kcp/blob/main/pkg/server/config.go#L116] which presumably is not initialized at the point of creating the config.

However in this case we're no longer using the shardExternalURL at all (the server from the new external-logical-cluster-admin-kubeconfig is used instead), so I removed the argument which passes the function.

File: pkg/authorization/bootstrap/policy.go [hunk 5]
```diff
@@ -76,6 +80,12 @@ func clusterRoles() []rbacv1.ClusterRole {
 				rbacv1helpers.NewRule("delete", "update", "get").Groups(tenancy.GroupName).Resources("workspaces").RuleOrDie(),
 			},
 		},
+		{
+			ObjectMeta: metav1.ObjectMeta{Name: SystemExternalLogicalClusterAdmin},
+			Rules: []rbacv1.PolicyRule{
+				rbacv1helpers.NewRule("delete", "update", "get").Groups(core.GroupName).Resources("logicalclusters", "logicalclusters/status").RuleOrDie(),
+			},
```
Comment (hardys) [inline pkg/authorization/bootstrap/policy.go:87]: @sttts and/or @s-urbaniak I added a new group as discussed but this rule doesn't seem to be enough to get logical clusters at cluster scope:

```
I0316 17:47:58.446040  572728 httplog.go:131] "HTTP" verb="GET" URI="/clusters/1jys1xdusxcx96v2/apis/core.kcp.io/v1alpha1/logicalclusters/cluster" latency="538.409µs" userAgent="kcp/v1.24.3+kcp (linux/amd64) kubernetes/b5751ce/kcp-workspace+root" audit-ID="a0d98940-2691-4798-8f98-a5148703ba03" srcIP="10.19.133.66:38396" resp=403
E0316 17:47:58.446644  572728 workspace_controller.go:225] "kcp-workspace" controller failed to sync "root|e2e-workspace-hktgw", err: logicalclusters.core.kcp.io "cluster" is forbidden: User "external-logical-cluster-admin" cannot get resource "logicalclusters" in API group "core.kcp.io" at the cluster scope: access denied
```

Any pointers on how to make the authz work without the short-circuit logic in the Authorizer like the regular `logical-cluster-admin` ?

File: pkg/reconciler/tenancy/workspace/workspace_controller.go (hunk 3 above)
Comment (davidfestal) [reply pkg/reconciler/tenancy/workspace/workspace_controller.go:123]: I use it in the upcoming Sharded Syncer PR, in this commit: https://github.com/kcp-dev/kcp/pull/2675/commits/d057305bfcf7fcaa62c652dedc36ef823e2cf48a

Backgound is that the virtual workspaces (either in the embedded or standalone mode) need to know the Shard External URL, in order to use it in their logic, especially the Syncer URL (cf our discussion about exposing the shard URL to the syncer as an annotation @sttts).

File: pkg/authorization/bootstrap/policy.go (hunk 5 above)
Comment (hardys) [reply pkg/authorization/bootstrap/policy.go:87]: After debugging with @s-urbaniak we concluded that the new `external-logical-cluster-admin` group still needs to be special-cased in the admission and content authorizer code (like the existing `logical-cluster-admin`), however we can avoid the special-casing in the requiredgroups authorizer, and the bootstrap policy rules are significantly more restrictive in the external case.

File: cmd/sharded-test-server/frontproxy.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (s-urbaniak) [reply cmd/sharded-test-server/frontproxy.go:315]: can we make a small comment here so future readers can reason about it as well?

File: pkg/admission/logicalcluster/admission.go [hunk 6]
```diff
@@ -191,7 +191,7 @@ func (o *plugin) Validate(ctx context.Context, a admission.Attributes, _ admissi
 			return fmt.Errorf("LogicalCluster cannot be deleted: %w", err)
 		}
 		groups := sets.NewString(a.GetUserInfo().GetGroups()...)
-		if !logicalCluster.Spec.DirectlyDeletable && !groups.Has(kuser.SystemPrivilegedGroup) && !groups.Has(bootstrap.SystemLogicalClusterAdmin) {
+		if !logicalCluster.Spec.DirectlyDeletable && !groups.Has(kuser.SystemPrivilegedGroup) && !groups.Has(bootstrap.SystemLogicalClusterAdmin) && !groups.Has(bootstrap.SystemExternalLogicalClusterAdmin) {
```
Comment (s-urbaniak) [inline pkg/admission/logicalcluster/admission.go:194]: i may misread: but if the user is external logical cluster admin, it already short-circuits in line 130, no?

File: pkg/authorization/bootstrap/policy.go [hunk 7]
```diff
@@ -39,6 +39,9 @@ const (
 	// This group allows it to skip the entire authorization stack except the bootstrap policy authorizer.
 	// Otherwise, the requests would be rejected because the LogicalCluster resource does not exist yet.
 	SystemLogicalClusterAdmin = "system:kcp:logical-cluster-admin"
+	// SystemExternalLogicalClusterAdmin is a group used by the scheduler to manage LogicalCluster resources.
```
Comment (s-urbaniak) [inline pkg/authorization/bootstrap/policy.go:42]: can we be a bit more precise what scheduler we mean?

Comment (s-urbaniak) [reply pkg/authorization/bootstrap/policy.go:42]: actually, we lack the same precision in the paragraph above as well :D

Comment (s-urbaniak) [reply pkg/authorization/bootstrap/policy.go:42]: additionally it would be great if we could expand on the difference to `system:kcp:logical-cluster-admin`.

File: pkg/authorization/workspace_content_authorizer.go [hunk 8]
```diff
@@ -116,6 +116,11 @@ func (a *workspaceContentAuthorizer) Authorize(ctx context.Context, attr authori
 		return DelegateAuthorization("logical cluster admin access", a.delegate).Authorize(ctx, attr)
 	}
 
+	// always let external-logical-cluster-admins through
+	if isUser && sets.NewString(attr.GetUser().GetGroups()...).Has(bootstrap.SystemExternalLogicalClusterAdmin) {
```
Comment (s-urbaniak) [inline pkg/authorization/workspace_content_authorizer.go:120]: `sets.NewString(attr.GetUser().GetGroups()...` is now used twice. as this fragment is invoked for every request I suggest to store it in a local variable.

File: pkg/proxy/options/authentication.go [hunk 9]
```diff
@@ -55,7 +56,7 @@ func NewAuthentication() *Authentication {
 			WithServiceAccounts().
 			WithTokenFile(),
 		// when adding new auth methods, also update AdditionalAuthEnabled below
-		DropGroups: []string{user.SystemPrivilegedGroup},
+		DropGroups: []string{user.SystemPrivilegedGroup, bootstrap.SystemLogicalClusterAdmin},
```
Comment (s-urbaniak) [inline pkg/proxy/options/authentication.go:59]: can we add a comment why we are doing this for `SystemLogicalClusterAdmin` ?

File: pkg/admission/logicalcluster/admission.go (hunk 6 above)
Comment (hardys) [reply pkg/admission/logicalcluster/admission.go:194]: Hmm yes, I just copied the existing `SystemLogicalClusterAdmin` but it seems the conditional should simply be `if !logicalCluster.Spec.DirectlyDeletable` as the other conditions are redundant - I'll add a commit to clean this up, thanks!

File: pkg/authorization/workspace_content_authorizer.go (hunk 8 above)
Comment (hardys) [reply pkg/authorization/workspace_content_authorizer.go]: Thanks, it's actually used three times, now moved to a `groups` variable :+1:

File: pkg/proxy/options/authentication.go (hunk 9 above)
Comment (hardys) [reply pkg/proxy/options/authentication.go:62]: Done

File: pkg/admission/logicalcluster/admission.go (hunk 6 above)
Comment (hardys) [reply pkg/admission/logicalcluster/admission.go]: Done

File: cmd/sharded-test-server/frontproxy.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (hardys) [reply cmd/sharded-test-server/frontproxy.go:318]: Done

**Comment by hardys** [comment]
/test e2e-sharded

Looks like #2865

File: pkg/reconciler/tenancy/workspace/workspace_reconcile.go [hunk 10]
```diff
@@ -97,14 +97,21 @@ func (c *Controller) reconcile(ctx context.Context, ws *tenancyv1alpha1.Workspac
 		return indexers.ByPathAndName[*tenancyv1alpha1.WorkspaceType](tenancyv1alpha1.Resource("workspacetypes"), c.globalWorkspaceTypeIndexer, path, name)
 	}
 
+	// create external client that goes through the front-proxy
+	externalConfig := restclient.CopyConfig(c.externalLogicalClusterAdminConfig)
+	kcpExternalClient, err := kcpclientset.NewForConfig(externalConfig)
```
Comment (s-urbaniak) [inline pkg/reconciler/tenancy/workspace/workspace_reconcile.go:102]: curiosity question: why does `kcpExternalClient` need to be instantiated at every reconciliation run? can't it be a cached member of `*Controller`?

Comment (hardys) [reply pkg/reconciler/tenancy/workspace/workspace_reconcile.go:102]: Thanks, you're right - I'll move it back to `workspace_controller.go` :+1:

**Comment by hardys** [comment]
@sttts this is ready for another review pass when you get time please - it's blocker for rebasing deployments based on the helm templates

File: pkg/authorization/workspace_content_authorizer.go [hunk 11]
```diff
@@ -112,10 +113,15 @@ func (a *workspaceContentAuthorizer) Authorize(ctx context.Context, attr authori
...
-	if isUser && sets.NewString(attr.GetUser().GetGroups()...).Has(bootstrap.SystemLogicalClusterAdmin) {
+	if isUser && groups.Has(bootstrap.SystemLogicalClusterAdmin) {
 		return DelegateAuthorization("logical cluster admin access", a.delegate).Authorize(ctx, attr)
 	}
 
+	// always let external-logical-cluster-admins through
+	if isUser && groups.Has(bootstrap.SystemExternalLogicalClusterAdmin) {
+		return DelegateAuthorization("external logical cluster admin access", a.delegate).Authorize(ctx, attr)
+	}
+
```
Comment (sttts) [inline pkg/authorization/workspace_content_authorizer.go:124]: this we don't want. Why is it necessary that the external logical cluster admin skips the existence test? It shouldn't.

Comment (hardys) [reply pkg/authorization/workspace_content_authorizer.go]: I moved it into the switch with the other checks
