### PR TITLE
syncer: fix hotloop & minor cleanup

### LINKED ISSUE #482: Syncer has a hot-loop
It doesn't return after calling AddRateLimited, so it immediately calls Forget on the key, which resets the rate limiter back to 0.

### PR DESCRIPTION
**Pull request by ncdc**
Fix a bug in the syncer where, after it got an error, it failed to
return immediately after adding the key back to the queue with a rate
limit. Because it didn't return immediately, the key was subsequently
forgotten (i.e. rate limit reset), which broke rate limited backoff.

Refactor the holder struct not to store an object instance, which is
consistent with standard controller/queue best practices.

Update the process method code to (hopefully) correctly determine the
"from" and "to" namespaces and item keys.

Fixes #482

### CODE REVIEW

File: pkg/syncer/syncer.go [hunk 1]
```diff
@@ -297,95 +321,106 @@ func PhysicalClusterNamespaceName(l NamespaceLocator) (string, error) {
...
 			return nil
 		}
 	} else {
 		nsInformer := c.fromInformers.ForResource(schema.GroupVersionResource{Version: "v1", Resource: "namespaces"})
-		nsObj, err := nsInformer.Lister().Get(clusters.ToClusterAwareKey(meta.GetClusterName(), namespace))
+
+		nsKey := fromNamespace
+		if h.clusterName != "" {
+			// If our "physical" cluster is a kcp instance (e.g. for testing purposes), it will return resources
+			// with metadata.clusterName set, whicih means their keys are cluster-aware, so we need to do the same here.
```
Comment (stevekuznetsov) [inline pkg/syncer/syncer.go:364]:
```suggestion
			// with metadata.clusterName set, which means their keys are cluster-aware, so we need to do the same here.
```

**Review by imjasonh — APPROVED** [review]

File: pkg/syncer/syncer.go (hunk 1 above)
Comment (ncdc) [reply pkg/syncer/syncer.go]: Thanks for catching, fixed!

**Review by stevekuznetsov — APPROVED** [review]
