### PR TITLE
Start centralizing APIExport indexers

### LINKED ISSUE #1752: APIExports virtual workspace broken when virtual workspaces are run standalone and an APIExport has permission claims
When the virtual workspaces process is run standalone, the virtual workspace for an APIExport with permission claims is broken because `indexers.IndexAPIExportByIdentity` is not configured (this only currently happens when the APIExport controller is instantiated, which does not happen in the virtual workspaces process).

### PR DESCRIPTION
**Pull request by ncdc**
## Summary
Move the definition of APIExport index functions needed across multiple controllers to pkg/indexers

## Related issue(s)

Fixes #1752

### CODE REVIEW

**Comment by ncdc** [comment]
ok i broke something, fixing

File: pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go [hunk 1]
```diff
@@ -76,7 +77,8 @@ func NewAPIReconciler(
 	}
 
 	if err := apiExportInformer.Informer().AddIndexers(cache.Indexers{
-		byWorkspace: indexByWorkspace,
+		byWorkspace:                  indexByWorkspace,
+		indexers.APIExportByIdentity: indexers.IndexAPIExportByIdentity,
```
Comment (shawn-hurley) [inline pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go:81]: is this potentially already added?

**Review by shawn-hurley — COMMENTED** [review]
Assuming that this is a stop-gap to allow for a standalone VW server, this looks good to me.

one question but otherwise looks good to me

File: pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go (hunk 1 above)
Comment (ncdc) [reply pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go]: that was the bug - refresh & see the latest 😄

**Comment by ncdc** [comment]
fixed my brokenness

**Comment by ncdc** [comment]
This won't cherry-pick cleanly to release-0.7, so I'll manually backport it

**Review by stevekuznetsov — APPROVED** [review]

**Comment by stevekuznetsov** [comment]
```
 pkg/indexers/util.go:58:49: non-wrapping format verb for fmt.Errorf. Use `%w` to format errors (errorlint)
		panic(fmt.Errorf("error adding indexers: %v", err))
		                                              ^ 
```

File: pkg/indexers/util.go [hunk 2]
```diff
@@ -43,3 +43,18 @@ func AppendOrDie(indexers ...cache.Indexers) cache.Indexers {
...
 	return ret
 }
+
+// AddIfNotPresentOrDie tries to add everything from toAdd to indexer's indexers that does not already exist. It panics
+// if it encounters an error.
+func AddIfNotPresentOrDie(indexer cache.Indexer, toAdd cache.Indexers) {
+	existing := indexer.GetIndexers()
+	for indexName := range toAdd {
+		if _, exists := existing[indexName]; exists {
+			delete(toAdd, indexName)
```
Comment (sttts) [inline pkg/indexers/util.go:53]: a pity function pointers cannot be compared

**Comment by ncdc** [comment]
Fixed lint

File: pkg/indexers/util.go (hunk 2 above)
Comment (shawn-hurley) [reply pkg/indexers/util.go:53]: This may seem silly, but this would cleanly allow during startup two indexers named the same but do two different things, right?

I feel like a bug like that would be hard to track down. Would it be worth the cost of using reflection to compare the function pointers?

https://pkg.go.dev/reflect#Value.Pointer

**Review by shawn-hurley — COMMENTED** [review]
This is exactly what I was thinking, just one minor point/question.

**Comment by ncdc** [comment]
> This may seem silly, but this would cleanly allow during startup two indexers named the same but do two different things, right?

It should be removing any indexes in `toAdd` that already exist, so they don't get added additional times.

**Comment by shawn-hurley** [comment]
The indexer function that was added before could do one set of behavior A, and the one added now could do different behavior B. This will currently just always choose A, which I was just suggesting could make debugging why you are not seeing behavior B a little challenging. If you compared the function pointers, I thought it would be worth saying these functions are not the same.

**Comment by ncdc** [comment]
@shawn-hurley I did some research, and there is not a reliable way to compare 2 function pointers (the only guarantee is you can compare them to `nil`).

**Comment by shawn-hurley** [comment]
/lgtm 

Sorry for sending you down the wrong path. I thought the reflection would work.
Can we add a v4 log or something then for when it does happen just to aid in debugging?
