### PR TITLE
cluster: scope-down dynamic and discovery clients

### LINKED ISSUE #236: Cluster controller unable to sync - can't find context
**Describe the bug**
The cluster controller is currently broken because of cluster name prefixing.

**To Reproduce**
1. Start kcp & cluster controller
2. Add a `Cluster` pointing at a valid cluster (e.g. kind)
3. `Cluster` status will eventually show an error like this:
```
error installing syncer: no context with the name of the expected cluster: 9-30-189-42-6443---user
```

**Expected behavior**
No error & syncer is installed.

**Additional context**
When we added cluster name prefixing, this breaks the cluster controller. @stevekuznetsov is working on some fixes to have the cluster controller use actual clients rather than kubeconfigs & contexts.

### PR DESCRIPTION
**Pull request by stevekuznetsov**
cluster: scope-down dynamic and discovery clients

Instead of expecting a separate kubeconfig context entry for every
possible logical cluster we need to operate over, use the client-go
helpers for scoping down a cluster-less dynamic client or discovery
client to a cluster-scoped one, as needed.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

requires https://github.com/kcp-dev/kubernetes/pull/22
Fixes #236

### CODE REVIEW

File: cmd/syncer/main.go [hunk 1]
```diff
@@ -18,7 +18,7 @@ const numThreads = 2
 
 var (
 	fromKubeconfig = flag.String("from_kubeconfig", "", "Kubeconfig file for -from cluster.")
-	fromContext    = flag.String("from_context", "", "Context to use in the Kubeconfig file for -from cluster, instead of the current context.")
+	fromCluster    = flag.String("from_cluster", "", "Name of the -from logical cluster.")
```
Comment (sttts) [inline cmd/syncer/main.go:21]: what is a name?

File: go.mod [hunk 2]
```diff
@@ -26,30 +26,30 @@ require (
...
-	k8s.io/kubectl => github.com/kcp-dev/kubernetes/staging/src/k8s.io/kubectl v0.0.0-20211118181850-ab2ca04a5894
-	k8s.io/kubelet => github.com/kcp-dev/kubernetes/staging/src/k8s.io/kubelet v0.0.0-20211118181850-ab2ca04a5894
-	k8s.io/kubernetes => github.com/kcp-dev/kubernetes v0.0.0-20211118181850-ab2ca04a5894
-	k8s.io/legacy-cloud-providers => github.com/kcp-dev/kubernetes/staging/src/k8s.io/legacy-cloud-providers v0.0.0-20211118181850-ab2ca04a5894
-	k8s.io/metrics => github.com/kcp-dev/kubernetes/staging/src/k8s.io/metrics v0.0.0-20211118181850-ab2ca04a5894
-	k8s.io/mount-utils => github.com/kcp-dev/kubernetes/staging/src/k8s.io/mount-utils v0.0.0-20211118181850-ab2ca04a5894
-	k8s.io/pod-security-admission => github.com/kcp-dev/kubernetes/staging/src/k8s.io/pod-security-admission v0.0.0-20211118181850-ab2ca04a5894
-	k8s.io/sample-apiserver => github.com/kcp-dev/kubernetes/staging/src/k8s.io/sample-apiserver v0.0.0-20211118181850-ab2ca04a5894
+	k8s.io/api => /home/stevekuznetsov/code/kcp-dev/kubernetes/src/github.com/kcp-dev/kubernetes/staging/src/k8s.io/api
```
Comment (sttts) [inline go.mod:29]: not to commit

File: cmd/syncer/main.go (hunk 1 above)
Comment (ncdc) [reply cmd/syncer/main.go:21]: Logical cluster name?

File: pkg/syncer/syncer.go [hunk 3]
```diff
@@ -100,14 +100,21 @@ func New(from, to *rest.Config, upsertFn UpsertFunc, deleteFn DeleteFunc, handle
 		namespace: os.Getenv(SyncerNamespaceKey),
 	}
 
-	fromClient := dynamic.NewForConfigOrDie(from)
-	fromDSIF := dynamicinformer.NewFilteredDynamicSharedInformerFactory(fromClient, resyncPeriod, metav1.NamespaceAll, func(o *metav1.ListOptions) {
+	fromClient, err := dynamic.NewClusterForConfig(from)
+	if err != nil {
+		return nil, err
+	}
+	fromDSIF := dynamicinformer.NewFilteredDynamicSharedInformerFactory(fromClient.Cluster(logicalClusterID), resyncPeriod, metav1.NamespaceAll, func(o *metav1.ListOptions) {
```
Comment (ncdc) [inline pkg/syncer/syncer.go:107]: Long-term, I'm guessing this will need to change so it's syncing against a "virtual view" of everything scheduled to "me" (my physical cluster or location), and not just from a single logical cluster?

File: go.mod (hunk 2 above)
Comment (stevekuznetsov) [reply go.mod:29]: The commit is labeled "TODO" for a reason :)

File: pkg/syncer/syncer.go (hunk 3 above)
Comment (stevekuznetsov) [reply pkg/syncer/syncer.go:107]: Yeah, I expect we will feed it a client capable of such a thing in the future

File: cmd/syncer/main.go (hunk 1 above)
Comment (stevekuznetsov) [reply cmd/syncer/main.go:21]: :)

**Comment by stevekuznetsov** [comment]
Fixes https://github.com/kcp-dev/kcp/issues/236

**Comment by ncdc** [comment]
Need to put the fixes details in the PR description to have it auto-close the issue on merge

**Comment by stevekuznetsov** [comment]
This is now just failing on syncing data back from the pcluster to the kcp, with:

```
E1123 12:06:36.406291 1604091 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: the server could not find the requested resource
```

**Comment by stevekuznetsov** [comment]
OK, should be working now. Added an e2e.

**Comment by stevekuznetsov** [comment]
Note: I will move both this and the sharding "e2e" into the Go-based tests once the framework lands. I know the shell is quite the mouthful but let's just use it as a stop-gap until we have the better approach.

File: pkg/reconciler/apiresource/negotiation.go [hunk 4]
```diff
@@ -552,21 +552,29 @@ func (c *Controller) ensureAPIResourceCompatibility(ctx context.Context, cluster
 		})
 	}
 	if negotiatedAPIResource == nil {
-		existing, err := c.kcpClient.ApiresourceV1alpha1().NegotiatedAPIResources().Create(ctx, newNegotiatedAPIResource, metav1.CreateOptions{})
```
Comment (sttts) [inline pkg/reconciler/apiresource/negotiation.go:555]: does this commit belong into the PR?

File: pkg/syncer/statussyncer.go [hunk 5]
```diff
@@ -27,7 +27,14 @@ func deepEqualStatus(oldObj, newObj interface{}) bool {
 	return equality.Semantic.DeepEqual(oldStatus, newStatus)
 }
 
+const statusSyncerAgent = "kcp#status-syncer/v0.0.0"
```
Comment (sttts) [inline pkg/syncer/statussyncer.go:30]: this is something I would like to see everywhere, for every controller and component we build. Is therre a good place to add this centrally? E.g. in the kcp startup code?

File: pkg/reconciler/apiresource/negotiation.go (hunk 4 above)
Comment (stevekuznetsov) [reply pkg/reconciler/apiresource/negotiation.go:555]: Not really, but it makes the test pass *way* faster, so ... :)

File: pkg/syncer/statussyncer.go (hunk 5 above)
Comment (stevekuznetsov) [reply pkg/syncer/statussyncer.go:30]: Yes, but //TODO?

File: pkg/reconciler/apiresource/negotiation.go (hunk 4 above)
Comment (stevekuznetsov) [reply pkg/reconciler/apiresource/negotiation.go]: Commit removed

File: pkg/syncer/statussyncer.go (hunk 5 above)
Comment (sttts) [reply pkg/syncer/statussyncer.go:30]: yes, as convention

**Review by sttts — APPROVED** [review]
