### PR TITLE
virtual: Support SSA patch requests for non-existent objects

### LINKED ISSUE #1852: bug: Server-side apply requests to virtual workspace API server fail for non-existent objects
### Describe the bug

A SSA patch request to the APIExport virtual workspace API server returns 404 when the corresponding object does not already exists.

### Steps To Reproduce

```golang
config := corev1apply.ConfigMap("config", "default").WithData(map[string]string{})
err = client.Patch(ctx, config, ctrl.Apply, ctrl.ForceOwnership, ctrl.FieldOwner("manager"))
```

### Expected Behaviour

SSA patch requests should succeed even when objects do not already exist.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by astefanutti**
## Summary

This PR switches update operations made to the virtual workspace API server, to calling create operations on the forwarding API server, for non-existent objects. This enables support for server-side apply patch requests in that case.

## Related issue(s)

Fixes #1852

### CODE REVIEW

File: pkg/virtual/framework/forwardingregistry/store.go [hunk 1]
```diff
@@ -273,3 +290,29 @@ func clientGetter(dynamicClusterClient dynamic.ClusterInterface, namespaceScoped
...
+}
+
+// hasUID return whether the provided object has a UID.
+func hasUID(obj runtime.Object) (bool, error) {
+	if obj == nil {
+		return false, nil
+	}
+	accessor, err := meta.Accessor(obj)
+	if err != nil {
+		return false, apierrors.NewInternalError(err)
```
Comment (sttts) [inline pkg/virtual/framework/forwardingregistry/store.go:312]: this is bad style: better move the `NewInternalError` wrapping to the top-level, if it is not already there.

File: pkg/virtual/framework/forwardingregistry/store.go [hunk 2]
```diff
@@ -192,7 +200,16 @@ func DefaultDynamicDelegatedStoreFuncs(
...
 
-			return delegate.Update(ctx, unstructuredObj, *options, subResources...)
+			// If the updated object does not have a UID, it means it doesn't currently exist.
+			// In that case, we switch to calling a create operation on the forwarding registry.
+			// This enables support for server-side apply requests, to create non-existent objects.
+			if hasUID, err := hasUID(unstructuredObj); err != nil {
+				return nil, err
+			} else if !hasUID {
+				return delegate.Create(ctx, unstructuredObj, updateToCreateOptions(options), subResources...)
+			} else {
```
Comment (sttts) [inline pkg/virtual/framework/forwardingregistry/store.go:210]: nit: drop last else

File: pkg/virtual/framework/forwardingregistry/store.go [hunk 3]
```diff
@@ -273,3 +290,29 @@ func clientGetter(dynamicClusterClient dynamic.ClusterInterface, namespaceScoped
...
 	}
 }
+
+// updateToCreateOptions creates a CreateOptions with the same field values as the provided PatchOptions.
+func updateToCreateOptions(uo *metav1.UpdateOptions) metav1.CreateOptions {
+	co := metav1.CreateOptions{
+		DryRun:          uo.DryRun,
+		FieldManager:    uo.FieldManager,
+		FieldValidation: uo.FieldValidation,
+	}
```
Comment (sttts) [inline pkg/virtual/framework/forwardingregistry/store.go:300]: this will bite us when UpdateOptiosn is extended. How can we catch that case, e.g. in unit tests. Even some reflection based check would be fine that UpdateOptions has not gotten new fields.

File: pkg/virtual/framework/forwardingregistry/store.go [hunk 4]
```diff
@@ -179,7 +181,13 @@ func DefaultDynamicDelegatedStoreFuncs(
...
 			oldObj, err := s.Get(ctx, name, &metav1.GetOptions{})
 			if err != nil {
-				return nil, err
+				if !apierrors.IsNotFound(err) {
+					return nil, err
+				}
+				// This is required to make the call to UpdatedObjectInfo.UpdatedObject pass.
+				oldObj = &unstructured.Unstructured{
+					Object: make(map[string]interface{}),
+				}
```
Comment (sttts) [inline pkg/virtual/framework/forwardingregistry/store.go:190]: worth an e2e test?

File: pkg/virtual/framework/forwardingregistry/store.go (hunk 2 above)
Comment (astefanutti) [reply pkg/virtual/framework/forwardingregistry/store.go]: done

File: pkg/virtual/framework/forwardingregistry/store.go (hunk 1 above)
Comment (astefanutti) [reply pkg/virtual/framework/forwardingregistry/store.go]: done

File: pkg/virtual/framework/forwardingregistry/store.go (hunk 4 above)
Comment (astefanutti) [reply pkg/virtual/framework/forwardingregistry/store.go]: Definitely, working on it 👍🏼

**Comment by astefanutti** [comment]
Added unit and e2e tests. Also added support for the `forceAllowCreate` argument to update operation.

**Comment by astefanutti** [comment]
@sttts @davidfestal PTAL.

File: pkg/virtual/framework/forwardingregistry/store.go (hunk 4 above)
Comment (astefanutti) [reply pkg/virtual/framework/forwardingregistry/store.go]: Added with 987273db6243279cb9ffa2b6d8f55dea57a0a78d.

File: pkg/virtual/framework/forwardingregistry/store.go [hunk 5]
```diff
@@ -176,10 +177,20 @@ func DefaultDynamicDelegatedStoreFuncs(
...
 		doUpdate := func() (*unstructured.Unstructured, error) {
 			oldObj, err := s.Get(ctx, name, &metav1.GetOptions{})
 			if err != nil {
-				return nil, err
+				// Continue on 404 when forceAllowCreate is enabled,
+				// or for PATCH requests, so server-side apply requests
+				// for non-existent objects can still be processed.
+				if !apierrors.IsNotFound(err) ||
+					!forceAllowCreate &&
+						!(requestInfo != nil && requestInfo.Verb == "patch") {
```
Comment (davidfestal) [inline pkg/virtual/framework/forwardingregistry/store.go:190]: What about `patch` requests which are not SSA requests ?
Will they try to create it as well ?

Comment (astefanutti) [reply pkg/virtual/framework/forwardingregistry/store.go:190]: For JSON or SMP patch requests, the corresponding patcher implementation returns a `errors.NewNotFound` error, so the response code is 404 as expected. The patchers execute as part of the `objInfo.UpdatedObject(ctx, oldObj)` call, and their implementations can be found at https://github.com/kubernetes/apiserver/blob/48405445f09218bb8b7a8a81eb21027cfd65761b/pkg/endpoints/handlers/patch.go, with the errors at:
- https://github.com/kubernetes/apiserver/blob/48405445f09218bb8b7a8a81eb21027cfd65761b/pkg/endpoints/handlers/patch.go#L355
- https://github.com/kubernetes/apiserver/blob/48405445f09218bb8b7a8a81eb21027cfd65761b/pkg/endpoints/handlers/patch.go#L451

Comment (davidfestal) [reply pkg/virtual/framework/forwardingregistry/store.go:190]: Thanks for the explanation.
Do you think you could add a comment in the code to explain this ? It's not easy to think of or guess when reading.

Comment (astefanutti) [reply pkg/virtual/framework/forwardingregistry/store.go:190]: Sure, I've added eb9e64dba2c064ebce3578c08ad8c2105ef002d3 that hopefully covers it.

I've also pushed 6d1b96804c3b9efb1a69cc49597fb6cfba6b4647 to have the use case covered in e2e tests.
