### PR TITLE
🐛 Fix incorrect cleaning of deletion annotations

### LINKED ISSUE #2287: bug: deletion annotation not removed when scheduler scheduled this resource again
### Describe the bug

When a resource has been scheduled to Synctarget A, and should then be scheduled to SyncTarget B, a deletion annotation is first added to the resource for Synctarget A. If, before the resource is completely removed from SyncTarget A, it is scheduled back to SyncTarget A, the deletion annotation for SyncTarget A is not removed.
This prevents further syncing to happen correctly.

### Steps To Reproduce

...

### Expected Behaviour

Deletion annotations should be updated correctly as it is the case for RequestState labels, from based on the namespace-based scheduling result.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by davidfestal**
## Summary

This PR fixes an incorrect cleaning of SyncTarget-related deletion annotations.

## Related issue(s)

Fixes #2287

### CODE REVIEW

**Review by qiujian16 — COMMENTED** [review]
/approve
/lgtm

File: pkg/reconciler/workload/resource/resource_reconcile_test.go [hunk 1]
```diff
@@ -188,6 +188,9 @@ func TestComputePlacement(t *testing.T) {
 			}, map[string]string{
 				"state.workload.kcp.dev/cluster-3": "Sync",
 			}, nil, nil, "ns"),
+			wantAnnotationPatch: map[string]interface{}{
```
Comment (davidfestal) [inline pkg/reconciler/workload/resource/resource_reconcile_test.go:191]: @sttts do you agree that the test was previously wrong, or was it on purpose that the deletion annotation would be kept even when rescheduling to the SyncTarget ?

Comment (sttts) [reply pkg/reconciler/workload/resource/resource_reconcile_test.go:191]: not sure. Leaving that to @qiujian16 and @jmprusi
