### PR TITLE
Fix: APIBinding read-modify-write race via Server-Side Apply

### LINKED ISSUE #3926: bug: APIBinding reconciler crash after first write produces ordering-dependent LogicalCluster recovery state
**Background**

I'm developing a tool that systematically explores controller reconciliation ordering, staleness, and fault injection ([kamera](https://github.com/tgoodwin/kamera)).

**Describe the bug**

I observe that when the APIBinding reconciler crashes after its first write effect, the LogicalCluster's conditions diverge during recovery.

The APIBinding reconciler's write sequence per reconcile:
1. [`apibinding_reconcile.go:310`](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/apis/apibinding/apibinding_reconcile.go#L310) — `updateLogicalCluster()`: writes resource locks to LogicalCluster
2. [`apibinding_reconcile.go:417-445`](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/apis/apibinding/apibinding_reconcile.go#L417-L445) — CRD creation in `system:bound-crds`
3. [`apibinding_reconcile.go:593-595`](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/apis/apibinding/apibinding_reconcile.go#L593-L595) — sets `InitialBindingCompleted=True`, `BindingUpToDate=True`, `Phase=Bound` (in-memory)
4. [`apibinding_controller.go:497`](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/apis/apibinding/apibinding_controller.go#L497) — `commit()`: patches APIBinding status to API server

A crash after write 1 (LogicalCluster update) but before write 4 (APIBinding status commit) leaves the APIBinding in an intermediate state where `InitialBindingCompleted` is not set. The LogicalClusterController then writes different conditions depending on what state it observes at recovery time — the intermediate APIBinding state causes different downstream condition evaluations depending on how far other controllers have progressed before the LogicalClusterController reconciles.

The resulting LogicalCluster conditions diverge because the LogicalClusterController reads different intermediate states depending on recovery ordering.

**Expected Behaviour**

After a crash and recovery, the LogicalCluster should converge to the same state regardless of which controller reconciles first.

**Proposed Fix**

`APIBinderInitializerController` and `DefaultAPIBindingLifecycleController` both write to LogicalCluster.Status concurrently, and the KCP committer ([`committer.go:129`](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/committer/committer.go#L129)) patches the *entire* status object. When both controllers read LogicalCluster, modify different conditions, and commit — the second commit's merge patch overwrites the first controller's condition changes because it includes the full status as that controller saw it (read-modify-write race).

I think the fix would be to use server-side apply (SSA) with a unique field manager per controller, rather than merge patch via the committer. With SSA, `APIBinderInitializerController` (field manager `apibinder-initializer`) would own `WorkspaceAPIBindingsInitialized` and `Status.Initializers`, while `DefaultAPIBindingLifecycleController` (field manager `default-apibinding-lifecycle`) would own `WorkspaceAPIBindingsReconciled`. Concurrent applies would not conflict because each controller only owns its specific fields.

**Additional Context**

The divergent LogicalCluster conditions persist as stable end states — the system converges to one of two distinct final states depending on recovery ordering, with no further reconciliation correcting the difference.

**Versions**

- kcp: v0.30.0 (commit `7952f476d`)
- Kubernetes: simulated via [kamera](https://github.com/tgoodwin/kamera) (based on k8s.io/client-go v0.35.0 / Kubernetes 1.35)

### PR DESCRIPTION
**Pull request by swastik959**
## Summary

This PR fixes the read-modify-write race condition that causes LogicalCluster and APIBinding conditions to diverge and overwrite each other, especially during crash recovery or concurrent reconciler runs.

Previously, the APIBinding controller relied on JSON Merge Patch and stale informer caches. If the controller crashed mid-flight, or if DefaultAPIBindingLifecycleController updated the cluster concurrently, intermediate conditions would be blindly erased. Furthermore, the reconciler was attempting to lock the cluster and generate CRDs before safely committing its initial Phase: Binding intent to the database.

Building on the infrastructure introduced in the SSA Committer PR, this PR implements the following fixes:

- Migrated APIBinding to SSA: Replaced the legacy MergePatch committer with NewSSACommitter for the APIBinding resource, using an explicit FieldManager.
- Targeted LogicalCluster Locks: Updated updateLogicalCluster to use Server-Side Apply (ApplyPatchType). By explicitly managing the payload, the reconciler now only asserts ownership over its specific locking annotations and conditions, rather than uploading the entire cluster object and wiping out sibling conditions.
- Crash-Proofed State Machine: Modified newReconciler to return reconcileStatusStopAndRequeue immediately after transitioning the object to Phase: Binding. This guarantees the intent is durably committed to etcd before the controller attempts heavy, conflict-prone operations like resource locking or CRD generation.
- Test Updates: Updated apibinding_reconcile_test.go to align with the new state machine expectations (expecting the requeue and appropriately deferring the Ready condition check).   

## What Type of PR Is This?
/kind bug

## Related Issue(s)

Fixes #3926 

## Release Notes

```release-note
NONE
```
## Testing Done

- Built and verified KCP locally.
- Created a wildwest-provider workspace and applied the cowboys APIExport and schemas.
- Created a wildwest-consumer workspace and applied the APIBinding.
- Verified that the APIBinding successfully reached phase: Bound and that all status conditions (Ready, APIExportValid, InitialBindingCompleted, PermissionClaimsApplied, etc.) merged flawlessly via SSA without overwriting one another.

### CODE REVIEW

File: pkg/reconciler/apis/apibinding/apibinding_controller.go [hunk 1]
```diff
@@ -492,8 +522,20 @@ func (c *controller) process(ctx context.Context, key string) (bool, error) {
...
-	newResource := &Resource{ObjectMeta: binding.ObjectMeta, Spec: &binding.Spec, Status: &binding.Status}
+	oldResource := &Resource{
+		APIVersion: "apis.kcp.io/v1alpha2",
+		Kind:       "APIBinding",
+		ObjectMeta: old.ObjectMeta,
+		Spec:       &old.Spec,
+		Status:     &old.Status,
+	}
+	newResource := &Resource{
+		APIVersion: "apis.kcp.io/v1alpha2",
```
Comment (mjudeikis) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go]: Just checking, how this would work (or won't work) if we're operating on `v1alpha1` ? We still have that api available. Need test for this.

File: pkg/reconciler/apis/apibinding/apibinding_controller.go [hunk 2]
```diff
@@ -156,12 +163,35 @@ func NewController(
 			return logicalClusterInformer.Lister().Cluster(name).Get(corev1alpha1.LogicalClusterName)
 		},
 		updateLogicalCluster: func(ctx context.Context, lc *corev1alpha1.LogicalCluster) error {
-			_, err := kcpClusterClient.CoreV1alpha1().LogicalClusters().Cluster(logicalcluster.From(lc).Path()).Update(ctx, lc, metav1.UpdateOptions{})
+			// FIXED: Pass the actual annotations from the LogicalCluster, not an empty map.
```
Comment (mjudeikis) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go]: comment with no value

File: pkg/reconciler/apis/apibinding/apibinding_controller.go [hunk 3]
```diff
@@ -67,6 +69,11 @@ var (
 	SystemBoundCRDsClusterName = logicalcluster.Name("system:bound-crds")
 )
 
+// boolPtr returns a pointer to a boolean value.
+func boolPtr(b bool) *bool {
```
Comment (mjudeikis) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go]: use [k8s](https://pkg.go.dev/k8s.io/utils/ptr)

File: pkg/reconciler/apis/apibinding/apibinding_controller.go [hunk 4]
```diff
@@ -156,12 +163,35 @@ func NewController(
 			return logicalClusterInformer.Lister().Cluster(name).Get(corev1alpha1.LogicalClusterName)
 		},
 		updateLogicalCluster: func(ctx context.Context, lc *corev1alpha1.LogicalCluster) error {
-			_, err := kcpClusterClient.CoreV1alpha1().LogicalClusters().Cluster(logicalcluster.From(lc).Path()).Update(ctx, lc, metav1.UpdateOptions{})
+			// FIXED: Pass the actual annotations from the LogicalCluster, not an empty map.
+			patchBytes, err := json.Marshal(map[string]interface{}{
```
Comment (mjudeikis) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go]: Now this is slippery slope. If this controller ever starts updating more than annotations in the code, it will start failing silently. we need some better safeguard for this logic

File: pkg/reconciler/apis/apibinding/apibinding_controller.go [hunk 5]
```diff
@@ -156,12 +163,35 @@ func NewController(
...
+				"apiVersion": "core.kcp.io/v1alpha1",
+				"kind":       "LogicalCluster",
```
Comment (mjudeikis) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go]: Not sure I like that we hardcoding versions, this will make version changing harder. do we have static values of these in sdk?

File: pkg/reconciler/apis/apibinding/apibinding_controller.go [hunk 6]
```diff
@@ -492,8 +522,20 @@ func (c *controller) process(ctx context.Context, key string) (bool, error) {
 	}
 
 	// If the object being reconciled changed as a result, update it.
-	oldResource := &Resource{ObjectMeta: old.ObjectMeta, Spec: &old.Spec, Status: &old.Status}
-	newResource := &Resource{ObjectMeta: binding.ObjectMeta, Spec: &binding.Spec, Status: &binding.Status}
+	oldResource := &Resource{
+		APIVersion: "apis.kcp.io/v1alpha2",
```
Comment (mjudeikis) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go]: same comment as above with versions

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go [hunk 7]
```diff
@@ -134,7 +134,8 @@ func (r *newReconciler) reconcile(ctx context.Context, apiBinding *apisv1alpha2.
 		"Waiting for API(s) to be established",
 	)
 
-	return reconcileStatusContinue, nil
+	// FIXED: Stop and requeue so the intent state commits BEFORE dangerous ops begin
```
Comment (mjudeikis) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go]: useless comment.

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go [hunk 8]
```diff
@@ -134,7 +134,8 @@ func (r *newReconciler) reconcile(ctx context.Context, apiBinding *apisv1alpha2.
...
+	return reconcileStatusStopAndRequeue, nil
```
Comment (mjudeikis) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go:137]: So does one exit from this reconciler? If it's always stopped? This looks wrong. Or feels wrong,.

**Review by mjudeikis — CHANGES_REQUESTED** [review]
quite a few comments :)

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go (hunk 8 above)
Comment (swastik959) [reply pkg/reconciler/apis/apibinding/apibinding_reconcile.go:137]: The newReconciler only executes when `Phase == ""`. By returning `StopAndRequeue`, we commit the Phase: Binding transition to etcd. The immediate requeue then routes the object into the bindingReconciler on the very next loop. Not sure if there is some other component getting affected though, any lead ?

File: pkg/reconciler/apis/apibinding/apibinding_controller.go (hunk 1 above)
Comment (swastik959) [reply pkg/reconciler/apis/apibinding/apibinding_controller.go]: Not sure I guess the code for controller is explicitly designed for interacting v1alpha2 
`type APIBinding = apisv1alpha2.APIBinding` I have an Idea that api server both in KCp and kubernetes is able to convert from v1alpha1 to v1alpha2 or am I missing something ?

**Comment by mjudeikis** [comment]
@swastik959 Some comments are not addressed. If something is not clear, please ask :)

**Comment by swastik959** [comment]
@mjudeikis I have commented on them not sure if they are visible or not 
Screenshot from 2026-04-15 13-46-02
Screenshot from 2026-04-15 13-45-50

**Comment by mjudeikis** [comment]
Its pending, you need to "submit your review" via review tab 
image

Github has 2 modes for comments:
1. Every comment is posted individually
2. Bulk post with full review (preferable) so all at once.

2nd helps with big reviews when you leave a comment and 2 files down, you get this "Oh, this is why this was done this way", and you can delete the comment as it's not yet posted :)

**Comment by swastik959** [comment]
@mjudeikis Thanks, was not aware about it :sweat_smile:

File: pkg/reconciler/apis/apibinding/apibinding_controller.go (hunk 6 above)
Comment (mjudeikis) [reply pkg/reconciler/apis/apibinding/apibinding_controller.go]: So the problem with this is that if somebody changes api 2 years later, this will not be cached on compile time. We tend to lose things like this in time :) so use api is preferable.

Comment (swastik959) [reply pkg/reconciler/apis/apibinding/apibinding_controller.go]: we can Just use 
`apisv1alpha2.SchemeGroupVersion.String()` for that case I believe instead of a simple string

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go (hunk 8 above)
Comment (swastik959) [reply pkg/reconciler/apis/apibinding/apibinding_reconcile.go:137]: @mjudeikis any leads on this ?

Comment (mjudeikis) [reply pkg/reconciler/apis/apibinding/apibinding_reconcile.go:137]: This sounds right, just need to read a code to remind myself.

File: pkg/reconciler/apis/apibinding/apibinding_controller.go [hunk 9]
```diff
@@ -156,12 +159,37 @@ func NewController(
...
 		updateLogicalCluster: func(ctx context.Context, lc *corev1alpha1.LogicalCluster) error {
-			_, err := kcpClusterClient.CoreV1alpha1().LogicalClusters().Cluster(logicalcluster.From(lc).Path()).Update(ctx, lc, metav1.UpdateOptions{})
+			patchObj := &corev1alpha1.LogicalCluster{
+				TypeMeta: metav1.TypeMeta{
+					APIVersion: corev1alpha1.SchemeGroupVersion.String(),
+					Kind:       "LogicalCluster",
+				},
+				ObjectMeta: metav1.ObjectMeta{
+					Name:        lc.Name,
+					Annotations: lc.Annotations,
```
Comment (mjudeikis) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go:169]: This patch will claim all annotations. I think it should just do one we care, else it basically takes over the supervision of all annotations.

it should own only one it needs to

File: pkg/reconciler/apis/apibinding/apibinding_controller.go [hunk 10]
```diff
@@ -156,12 +159,37 @@ func NewController(
...
+				return err
+			}
+			_, err = kcpClusterClient.CoreV1alpha1().LogicalClusters().Cluster(logicalcluster.From(lc).Path()).Patch(
+				ctx,
+				lc.Name,
+				types.ApplyPatchType,
+				patchBytes,
+				metav1.PatchOptions{
+					FieldManager: "apibinding-reconciler-locks",
+					Force:        ptr.To(true),
```
Comment (mjudeikis) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go:183]: I wonder if we make this only annotation owned, do we need force here?

**Comment by mjudeikis** [comment]
In addition there are other reconcilers writing LC status:
```
`kcp-logicalcluster` is a merge-patch committer and a real candidate to race on LogicalCluster.Status.
Workspace tenancy controllers under `pkg/reconciler/tenancy/` also write LogicalCluster.Status (phase, initializers, conditions) and should be audited.
```

Basically this fix work only if all places are changed.

File: pkg/reconciler/apis/apibinding/apibinding_controller.go [hunk 11]
```diff
@@ -156,12 +159,37 @@ func NewController(
...
+			if err != nil {
+				return err
+			}
+			_, err = kcpClusterClient.CoreV1alpha1().LogicalClusters().Cluster(logicalcluster.From(lc).Path()).Patch(
+				ctx,
+				lc.Name,
+				types.ApplyPatchType,
+				patchBytes,
+				metav1.PatchOptions{
+					FieldManager: "apibinding-reconciler-locks",
```
Comment (mjudeikis) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go:182]: Move this close to controller name ontop:
```
FieldManager = "apibinding-reconciler-locks"
```

**Review by mjudeikis — COMMENTED** [review]
Sorry, this takes a while. This is a VERY sensitive write path. So we need to get this right, and it's not straightforward. Every round of reviews is like gizza piramide digging and looking for secret chambers. 

But we are on the right path :)

File: pkg/reconciler/apis/apibinding/apibinding_controller.go (hunk 10 above)
Comment (swastik959) [reply pkg/reconciler/apis/apibinding/apibinding_controller.go:186]: I tested dropping Force: ptr.To(true), but it results in immediate SSA conflicts: Apply failed with 1 conflict: conflict with "kcp" using core.kcp.io/v1alpha1: .metadata.annotations.internal.apis.kcp.io/resource-bindings.

Because the core "kcp" field manager (or mutating webhooks) frequently touches the LogicalCluster annotations, our apibinding-reconciler-locks manager must use Force: true to successfully acquire shared ownership of this specific key during the binding process without throwing conflict errors.

Comment (swastik959) [reply pkg/reconciler/apis/apibinding/apibinding_controller.go:186]: @mjudeikis please feel free to review the changes and comment whenever you feel right

Comment (mjudeikis) [reply pkg/reconciler/apis/apibinding/apibinding_controller.go:186]: checking again. sorry, was bit swamped

**Comment by mjudeikis** [comment]
last comment :D and we can merge

**Test gap on the new `StopAndRequeue` ordering**

`TestReconcileNew` covers reconcile #1 (Phase=Binding, no Ready). `TestReconcileBinding` covers reconcile #2 with a hand-crafted `Phase=Binding` input. Nothing chains them on the same object.

That means someone could revert [`apibinding_reconcile.go:137`](https://github.com/kcp-dev/kcp/blob/apibinding/commiter/pkg/reconciler/apis/apibinding/apibinding_reconcile.go#L137) back to `reconcileStatusContinue`, or add a `MarkFalse(Ready, ...)` before the early return, and both existing tests still pass. The "Phase commits before conditions" guarantee this PR is built around is unguarded.

Could you add a two-call sequence test? Something like:

```go
// reconcile #1 — fresh binding, no Phase
requeue, err := c.reconcile(ctx, apiBinding)
require.NoError(t, err)
require.True(t, requeue)
require.Equal(t, apisv1alpha2.APIBindingPhaseBinding, apiBinding.Status.Phase)
require.False(t, conditions.Has(apiBinding, conditionsv1alpha1.ReadyCondition))

// reconcile #2 — same object, simulate the requeue
_, err = c.reconcile(ctx, apiBinding)
require.NoError(t, err)
require.True(t, conditions.Has(apiBinding, conditionsv1alpha1.ReadyCondition))
```

Small and mechanical, but it pins the ordering the PR introduces.

**Comment by swastik959** [comment]
@mjudeikis Done

**Review by mjudeikis — APPROVED** [review]
/lgtm
/approve
