### PR TITLE
✨  Implement `RulesFor` for `GlobalAuthorizer` and `LocalAuthorizer` to enable `SelfSubjectRulesReview`

### LINKED ISSUE #1924: bug: API server panics on SelfSubjectRulesReview requests
### Describe the bug

SSR requests to a workspace API server return abruptly.

The stack trace points to the `github.com/kcp-dev/kcp/pkg/authorization.(*LocalAuthorizer).RulesFor` method:
```
E0908 20:41:51.897726   84042 wrap.go:57] "apiserver panic'd" method="POST" URI="/clusters/root:camel-k:demo/apis/authorization.k8s.io/v1/selfsubjectrulesreviews" audit-ID="fc6f0ebc-24da-4945-b682-15749be88389"
http2: panic serving 192.168.0.24:50693: implement me
goroutine 405181 [running]:
k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest.func1.1()
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220901103730-c8d74a9d456b/pkg/endpoints/handlers/finisher/finisher.go:105 +0x118
panic({0x7d19680, 0x86e7a90})
        /usr/local/opt/go/libexec/src/runtime/panic.go:890 +0x267
github.com/kcp-dev/kcp/pkg/authorization.(*LocalAuthorizer).RulesFor(0xc0003ca190, {0x872e7e8, 0xc00b49f800}, {0xc01e6f08c8, 0x7})
        /Users/antonin/Development/kcp/pkg/authorization/local_authorizer.go:65 +0x6f
k8s.io/apiserver/pkg/authorization/union.unionAuthzRulesHandler.RulesFor({0xc000133640, 0x2, 0x2}, {0x872e7e8, 0xc00b49f800}, {0xc01e6f08c8, 0x7})
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220901103730-c8d74a9d456b/pkg/authorization/union/union.go:89 +0x2f9
k8s.io/kubernetes/pkg/registry/authorization/selfsubjectrulesreview.(*REST).Create(0xc001061c70, {0x872d358, 0xc01ef32ab0}, {0x87148c8, 0xc018ffb980}, 0xc01c2ba940, 0xc01685a3c0)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes@v0.0.0-20220901103730-c8d74a9d456b/pkg/registry/authorization/selfsubjectrulesreview/rest.go:81 +0x2f1
k8s.io/apiserver/pkg/endpoints/handlers.(*namedCreaterAdapter).Create(0xc01e9e2c10, {0x872d358, 0xc01ef32ab0}, {0x0, 0x0}, {0x87148c8, 0xc018ffb980}, 0xc01c2ba940, 0xc01685a3c0)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220901103730-c8d74a9d456b/pkg/endpoints/handlers/create.go:247 +0xd3
k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1.1()
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220901103730-c8d74a9d456b/pkg/endpoints/handlers/create.go:177 +0x153
k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1.2()
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220901103730-c8d74a9d456b/pkg/endpoints/handlers/create.go:203 +0x622
k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest.func1()
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220901103730-c8d74a9d456b/pkg/endpoints/handlers/finisher/finisher.go:117 +0x10b
created by k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220901103730-c8d74a9d456b/pkg/endpoints/handlers/finisher/finisher.go:92 +0x10a
```

### Steps To Reproduce

```
$ curl -v -k \
    -X POST \
    -d @- \
    -H "Authorization: Bearer <REDACTED>" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    https://192.168.0.24:6443/clusters/root:default:test/apis/authorization.k8s.io/v1/selfsubjectrulesreviews <<'EOF'
{
  "kind": "SelfSubjectRulesReview",
  "apiVersion": "authorization.k8s.io/v1",
  "spec": {
    "namespace": "default"
  }
}
EOF
* HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
* stopped the pause stream!
* Connection #0 to host 192.168.0.24 left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

### Expected Behaviour

It should be possible to perform SSR requests.

### Additional Context

SAR requests return successfully, e.g.:

```
$ curl -v -k \
    -X POST \
    -d @- \
    -H "Authorization: Bearer <REDACTED>" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    https://192.168.0.24:6443/clusters/root:default:test/apis/authorization.k8s.io/v1/selfsubjectaccessreviews <<'EOF'
{
  "kind": "SelfSubjectAccessReview",
  "apiVersion": "authorization.k8s.io/v1",
  "spec": {
    "namespace": "default",
    "resourceAttributes": {
      "group": "apps",
      "resource": "deployment"
    }
  }
}
EOF
< HTTP/2 201
< audit-id: 7f143413-20e6-4174-bc9a-38694849880f
< cache-control: no-cache, private
< content-type: application/json
< x-kubernetes-pf-flowschema-uid:
< x-kubernetes-pf-prioritylevel-uid:
< content-length: 876
< date: Thu, 08 Sep 2022 18:49:20 GMT
<
{
  "kind": "SelfSubjectAccessReview",
  "apiVersion": "authorization.k8s.io/v1",
  "spec": {
    "resourceAttributes": {
      "group": "apps",
      "resource": "deployment"
    }
  },
  "status": {
    "allowed": true,
    "reason": "RBAC: allowed by ClusterRoleBinding \"system:kcp:clusterworkspace:admin\" of ClusterRole \"cluster-admin\" to Group \"system:kcp:clusterworkspace:admin\""
  }
* Connection #0 to host 192.168.0.24 left intact
}%
```

### PR DESCRIPTION
**Pull request by embik**
## Summary

This PR implements the stub `RulesFor` methods for both `GlobalAuthorizer` and `LocalAuthorizer` to enable usage of the `SelfSubjectRulesReview` API. I'll be completely honest, this felt "too easy", so I hope I'm doing the correct thing here. Output of `kubectl auth can-i --list` looked sensible to me.

Basically, I've aligned the way both the global and the local authorizer generate their cluster-specific authorizer and just called `RulesFor` on the scoped authorizer created from it. After PR review, I've also added two e2e test cases that make sure that the `SelfSubjectRulesReview` API gives expected responses.

On a minor note, this PR cleans up the `OWNERS` file because it's from the before times (unless we want to keep access to this package limited, which might be fair).

## Related issue(s)

Fixes #1924

## Release Notes

```release-note
Implement `SelfSubjectRulesReview` API, enabling usage of e.g. `kubectl auth can-i --list`
```

### CODE REVIEW

File: pkg/authorization/local_authorizer.go [hunk 1]
```diff
@@ -33,26 +33,38 @@ import (
 )
 
 type LocalAuthorizer struct {
-	roleLister               rbacv1listers.RoleClusterLister
-	roleBindingLister        rbacv1listers.RoleBindingClusterLister
-	clusterRoleBindingLister rbacv1listers.ClusterRoleBindingClusterLister
-	clusterRoleLister        rbacv1listers.ClusterRoleClusterLister
```
Comment (sttts) [inline pkg/authorization/local_authorizer.go:39]: these were intentional I believe to ensure the informers are started. If you move them into the hot path, the `Lister()` call might come to later after the shared informer factory has been started. Creates ugly races.

File: pkg/authorization/global_authorizer.go [hunk 2]
```diff
@@ -58,8 +58,13 @@ func NewGlobalAuthorizer(localKubeInformers, globalKubeInformers kcpkubernetesin
...
 func (a *GlobalAuthorizer) RulesFor(ctx context.Context, user user.Info, namespace string) ([]authorizer.ResourceRuleInfo, []authorizer.NonResourceRuleInfo, bool, error) {
-	// TODO: wire context in RulesFor interface
-	panic("implement me")
+	cluster := genericapirequest.ClusterFrom(ctx)
+	if cluster == nil || cluster.Name.Empty() {
+		return nil, nil, false, fmt.Errorf("empty cluster name")
+	}
+
+	scopedAuth := a.newAuthorizer(cluster.Name)
+	return scopedAuth.RulesFor(ctx, user, namespace)
```
Comment (sttts) [inline pkg/authorization/global_authorizer.go:67]: How about a small e2e to ensure `SelfSubjectAccessReview` works?

File: pkg/authorization/local_authorizer.go (hunk 1 above)
Comment (mjudeikis) [reply pkg/authorization/local_authorizer.go:39]: code comment would be good if this is the case

Comment (embik) [reply pkg/authorization/local_authorizer.go:39]: Yeah, let me bring this back and add a note. I wasn't aware of this and thought they were just written at different times and there was room to unify the code.

Comment (embik) [reply pkg/authorization/local_authorizer.go:39]: I'll do a little PR history search if I can find some additional context.

Comment (sttts) [reply pkg/authorization/local_authorizer.go:39]: we do similar things in the controllers. They all store listers in their struct to enforce creation of the informers at constructor time.

File: pkg/authorization/global_authorizer.go (hunk 2 above)
Comment (embik) [reply pkg/authorization/global_authorizer.go:67]: Sounds sensible. Will take a look at that.

File: pkg/authorization/local_authorizer.go (hunk 1 above)
Comment (embik) [reply pkg/authorization/local_authorizer.go:39]: Question here: Should we adjust the `GlobalAuthorizer` as well then? Because I copied this pattern from it, so it would be susceptible to the same races, no? Is there something with the `localKubeInformers` and `globalKubeInformers` passed to _that_ that makes it okay?

Comment (embik) [reply pkg/authorization/local_authorizer.go:39]: Deleted my previous comment by mistake. I copied this pattern over from the `GlobalAuthorizer`, which also takes `SharedInformerFactory` input parameters. Should we adjust that one as well, or is there something special with it that will prevent those races mentioned?

**Comment by embik** [comment]
@sttts @mjudeikis ready for re-review.

**Comment by embik** [comment]
/retest

looks like flakes ...? Let's see. Tests are not related I think, but maybe I broke something.

File: pkg/authorization/global_authorizer.go [hunk 3]
```diff
@@ -33,33 +34,42 @@ import (
...
-				)},
-				&rbac.RoleBindingLister{Lister: globalKubeInformers.Rbac().V1().RoleBindings().Lister().Cluster(clusterName)},
-				&rbac.ClusterRoleGetter{Lister: rbacwrapper.NewMergedClusterRoleLister(
-					globalKubeInformers.Rbac().V1().ClusterRoles().Lister().Cluster(clusterName),
-					localKubeInformers.Rbac().V1().ClusterRoles().Lister().Cluster(controlplaneapiserver.LocalAdminCluster),
-				)},
-				&rbac.ClusterRoleBindingLister{Lister: globalKubeInformers.Rbac().V1().ClusterRoleBindings().Lister().Cluster(clusterName)},
-			)
-		},
+		globalRoleLister: globalKubeInformers.Rbac().V1().Roles().Lister(),
```
Comment (sttts) [inline pkg/authorization/global_authorizer.go:51]: nit: globalRoles

Would be less noisy.

File: pkg/authorization/local_authorizer.go [hunk 4]
```diff
@@ -41,6 +42,7 @@ type LocalAuthorizer struct {
 
 func NewLocalAuthorizer(versionedInformers kcpkubernetesinformers.SharedInformerFactory) (authorizer.Authorizer, authorizer.RuleResolver) {
 	a := &LocalAuthorizer{
+		// listers are saved in the struct here to ensure that informers are started and we do not encounter race conditions with them.
```
Comment (sttts) [inline pkg/authorization/local_authorizer.go:45]: nit: are instantiated early and ... with starting them

File: pkg/authorization/global_authorizer.go (hunk 3 above)
Comment (embik) [reply pkg/authorization/global_authorizer.go:51]: I tried to keep it consistent with `LocalAuthorizer`, which looks like this:

```go
a := &LocalAuthorizer{
    // listers are saved in the struct here to ensure that informers are started and we do not encounter race conditions with them.
    roleLister:               versionedInformers.Rbac().V1().Roles().Lister(),
    roleBindingLister:        versionedInformers.Rbac().V1().RoleBindings().Lister(),
    clusterRoleLister:        versionedInformers.Rbac().V1().ClusterRoles().Lister(),
    clusterRoleBindingLister: versionedInformers.Rbac().V1().ClusterRoleBindings().Lister(),
}
```

**Comment by sttts** [comment]
Some nits.

/lgtm
/approve
/hold

if you want to address the nits.

File: pkg/authorization/local_authorizer.go (hunk 4 above)
Comment (embik) [reply pkg/authorization/local_authorizer.go]: Much clearer, thanks. Updated the comments.

**Comment by embik** [comment]
/hold cancel

Addressed comment nit. I'm not 100% sure how to proceed with the lister fields, but from my perspective it's okay, so this can go in with an lgtm.
