### PR TITLE
🐛 Fix root phase 0 bootstrapping sometimes failing

### LINKED ISSUE #2148: bug: root phase 0 bootstrapping can fail and return early from the kcp-start-informers poststart hook
### Describe the bug

root phase 0 bootstrapping can fail and return early from the kcp-start-informers poststart hook.

**/readyz** returns not ready forever

### Steps To Reproduce

1. Start kcp, let it fully bootstrap and become ready
2. Shut it down
3. Start it up again
4. You might see `failed to bootstrap root workspace phase 0` in the log with an error that an APIBinding could not be updated due to a conflict

### Expected Behaviour

Retry the update, don't return nil from the post start hook

### Additional Context

https://github.com/kcp-dev/kcp/blob/047c62dc797452d218260d342842f059290bac68/pkg/server/server.go#L180-L188

says `don't klog.Fatal. This only happens when context is cancelled` but that's not 100% true in this case. `configrootphase0.Bootstrap` calls 

https://github.com/kcp-dev/kcp/blob/047c62dc797452d218260d342842f059290bac68/config/root-phase0/bootstrap.go#L39

which does not block until success:

https://github.com/kcp-dev/kcp/blob/047c62dc797452d218260d342842f059290bac68/config/helpers/bootstrap.go#L275-L277

### PR DESCRIPTION
**Pull request by ncdc**
## Summary
Make sure that when binding root APIs, we keep retrying updates until they succeed.

## Related issue(s)

Fixes #2148

### CODE REVIEW

File: config/helpers/bootstrap.go [hunk 1]
```diff
@@ -261,22 +262,39 @@ func BindRootAPIs(ctx context.Context, kcpClient kcpclient.Interface, exportName
...
 		if !apierrors.IsAlreadyExists(err) {
 			return err
 		}
 
-		existing, err := kcpClient.ApisV1alpha1().APIBindings().Get(ctx, exportName, metav1.GetOptions{})
-		if err != nil {
+		if err := wait.PollImmediateInfiniteWithContext(ctx, time.Second, func(ctx context.Context) (bool, error) {
+			existing, err := kcpClient.ApisV1alpha1().APIBindings().Get(ctx, exportName, metav1.GetOptions{})
+			if err != nil {
+				return false, err
```
Comment (stevekuznetsov) [inline config/helpers/bootstrap.go:276]: Why is it ok for this to return `err` and fail?

Comment (ncdc) [reply config/helpers/bootstrap.go:276]: You're right, this hides the same issue I am trying to fix. If we get an already-exists error trying to create, and then the get request fails, we're probably in some weird perma-fail state at that point. Could log + return `false, nil`, could panic...?

Comment (ncdc) [reply config/helpers/bootstrap.go]: Updated so we never return an error and always keep retrying
