### PR TITLE
Prevent workspace deletion leaks

### LINKED ISSUE #3350: bug: Creating and then deleting workspaces causes leaked goroutines
### Describe the bug

baseline pprof from kcp before workspace creation/deletion: 
[pre-ws.pprof.txt](https://github.com/user-attachments/files/19456964/pre-ws.pprof.txt)

pprof after creating and then deleting an org workspace 100 times:
[post-ws.pprof.txt](https://github.com/user-attachments/files/19456977/post-ws.pprof.txt)

go tool rendering of pprof:

Image

### Steps To Reproduce

1. Patch kcp to enable pprof
[addpprof.patch](https://github.com/user-attachments/files/19457006/addpprof.patch)
2. Start kcp in tilt and set the kubeconfig to the kind cluster
3. port forward pprof port: `kubectl port-forward -n kcp-alpha deployment/alpha 6060:6060 &`
4. get a baseline pprof: `http://localhost:6060/debug/pprof/goroutine > pre-ws.pprof`
5. create a simple yaml file for an organization workspace: [org-ws.yaml.txt](https://github.com/user-attachments/files/19457044/org-ws.yaml.txt)
6. target kcp, and then create and delete the same org 100 times in a loop: `for i in {1..100}; do k apply -f org-ws.yaml; sleep 3; k delete -f org-ws.yaml; sleep 3; done`
7. collect pprof again and observe the large number of goroutines.

### Expected Behaviour

Fewer goroutines

### Additional Context

This looks related to #3016 although that issue is long since fixed, and didn't require new workspaces.

As far as I can tell, creating a new workspace causes the creation of listeners that wont get cancelled until the sharedIndexInformer is terminated.

### PR DESCRIPTION
**Pull request by ntnn**
## Summary

Fix workspace deletion leaks as found in #3350 

## What Type of PR Is This?

/kind bug

## Related Issue(s)

Fixes #3350

## Release Notes

```release-note
Prevent goroutine leaks when deleting workspaces
```

### CODE REVIEW

**Comment by ntnn** [comment]
/hold 

Until after 0.28 released

File: pkg/admission/mutatingwebhook/plugin.go [hunk 1]
```diff
@@ -200,4 +211,51 @@ func (p *Plugin) SetKcpInformers(local, global kcpinformers.SharedInformerFactor
 	p.getAPIBindings = func(clusterName logicalcluster.Name) ([]*apisv1alpha2.APIBinding, error) {
 		return local.Apis().V1alpha2().APIBindings().Lister().Cluster(clusterName).List(labels.Everything())
 	}
+
+	// handler doesn't need to be deregistered - the webhook is valid
+	// for as long as kcp runs and when kcp stops the informer the
```
Comment (ntnn) [inline pkg/admission/mutatingwebhook/plugin.go]:
```suggestion
	// for as long as kcp runs and when kcp stops the informer is stopped as well the
```

File: pkg/admission/validatingwebhook/plugin.go [hunk 2]
```diff
@@ -199,6 +210,49 @@ func (p *Plugin) SetKcpInformers(local, global kcpinformers.SharedInformerFactor
 	p.getAPIBindings = func(clusterName logicalcluster.Name) ([]*apisv1alpha2.APIBinding, error) {
 		return local.Apis().V1alpha2().APIBindings().Lister().Cluster(clusterName).List(labels.Everything())
 	}
+
+	// handler doesn't need to be deregistered - the webhook is valid
+	// for as long as kcp runs and when kcp stops the informer the
```
Comment (ntnn) [inline pkg/admission/validatingwebhook/plugin.go]:
```suggestion
	// for as long as kcp runs and when kcp stops the informer is stopped as well the
```

File: pkg/admission/mutatingwebhook/plugin.go [hunk 3]
```diff
@@ -55,11 +60,13 @@ type Plugin struct {
 	kubeClusterClient               kcpkubernetesclientset.ClusterInterface
 	localKubeSharedInformerFactory  kcpkubernetesinformers.SharedInformerFactory
 	globalKubeSharedInformerFactory kcpkubernetesinformers.SharedInformerFactory
+	serverStopChannel               <-chan struct{}
```
Comment (ntnn) [inline pkg/admission/mutatingwebhook/plugin.go:61]: need to add this to the plugin validation

File: pkg/admission/mutatingwebhook/plugin.go [hunk 4]
```diff
@@ -200,4 +211,51 @@ func (p *Plugin) SetKcpInformers(local, global kcpinformers.SharedInformerFactor
...
+			clName := logicalcluster.Name(cl.Annotations[logicalcluster.AnnotationKey])
+
+			p.managerLock.RLock()
+			cancel, ok := p.managersCancel[clName]
+			p.managerLock.RUnlock()
+			if !ok {
+				return
+			}
+
+			// TODO ensure this is only run once
```
Comment (ntnn) [inline pkg/admission/mutatingwebhook/plugin.go]: maybe put this into a sync.once in a map next to the manager and cancel

File: test/integration/framework/goleak.go [hunk 5]
```diff
@@ -24,74 +24,17 @@ import (
 )
 
 var (
+	// KnownGoroutineLeaks are leaks from just running KCP collected
+	// with TestGoleakWithDefaults and run through:
+	//	grep 'on top of the stack' output.log | cut -d, -f2- | cut -d' ' -f3 | sort | uniq
```
Comment (ntnn) [inline test/integration/framework/goleak.go]: Most of the leaks were just KCP not shutting down properly because it was stopped too fast after reporting ready, as noted in #3488 
The leftover are probably similar things as in the webhooks - goroutines or informer hooks that were started but never bound by a context.

File: test/integration/framework/goleak.go [hunk 6]
```diff
@@ -1,114 +0,0 @@
...
-// Goleak tests cannot be run in parallelized tests.
-func GoleakWithDefaults(tb testing.TB, in ...goleak.Option) {
-	tb.Helper()
-
-	tb.Logf("waiting %v for goroutines to finish", WaitTime)
-	time.Sleep(WaitTime)
-
-	opts := append(KnownGoroutineLeaks, in...)
-	goleak.VerifyNone(tb, opts...)
-}
```
Comment (ntnn) [inline test/integration/framework/goleak.go:114]: So the idea here was to use IgnoreCreatedBy to ignore any goroutines started by KCP when testing a component for leaks. However that requires the PR to be merged: https://github.com/uber-go/goleak/pull/136

Since that doesn't seem to happen anytime soon I removed the entire helper function. The leak test for KCP itself is in framework/leak_test for now, the workspace leak test in workspace/leak_test.

File: pkg/admission/mutatingwebhook/plugin.go [hunk 7]
```diff
@@ -200,4 +212,34 @@ func (p *Plugin) SetKcpInformers(local, global kcpinformers.SharedInformerFactor
 	p.getAPIBindings = func(clusterName logicalcluster.Name) ([]*apisv1alpha2.APIBinding, error) {
 		return local.Apis().V1alpha2().APIBindings().Lister().Cluster(clusterName).List(labels.Everything())
 	}
+
+	// handler doesn't need to be deregistered - the webhook is valid
+	// for as long as kcp runs and when kcp stops the informer is
+	// stopped and the handler gets cleaned up.
+	informer := local.Core().V1alpha1().LogicalClusters().Informer()
+	_, _ = informer.AddEventHandler(cache.ResourceEventHandlerFuncs{
```
Comment (ntnn) [inline pkg/admission/mutatingwebhook/plugin.go]:
```suggestion
	_, _ = local.Core().V1alpha1().LogicalClusters().Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
```

File: pkg/admission/validatingwebhook/plugin.go [hunk 8]
```diff
@@ -199,6 +211,32 @@ func (p *Plugin) SetKcpInformers(local, global kcpinformers.SharedInformerFactor
 	p.getAPIBindings = func(clusterName logicalcluster.Name) ([]*apisv1alpha2.APIBinding, error) {
 		return local.Apis().V1alpha2().APIBindings().Lister().Cluster(clusterName).List(labels.Everything())
 	}
+
+	// handler doesn't need to be deregistered - the webhook is valid
+	// for as long as kcp runs and when kcp stops the informer is
+	// stopped and the handler gets cleaned up.
+	informer := local.Core().V1alpha1().LogicalClusters().Informer()
+	_, _ = informer.AddEventHandler(cache.ResourceEventHandlerFuncs{
```
Comment (ntnn) [inline pkg/admission/validatingwebhook/plugin.go]:
```suggestion
	_, _ = local.Core().V1alpha1().LogicalClusters().Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
```

**Comment by ntnn** [comment]
I'm not entirely sure why but the leak test always failed immediately [with `kcptesting.Eventually`](https://github.com/kcp-dev/kcp/commit/c00bc30813c1874b215da5ead13100d64dcc2ee0). Using `require.EventuallyWitht` seems stable:

image

**Review by embik — APPROVED** [review]
/approve

🚀
