### PR TITLE
Stop apiimporter, syncer, heartbeat from fighting over the Ready condition

### LINKED ISSUE #865: apiimport_manager, push/pull managers, and heartbeat manager fight over workload cluster readiness
**Describe the bug**
If a workload cluster becomes not ready, various controllers update the Ready condition with different reasons and messages. This causes them to hotloop fighting over the condition.

**To Reproduce**
1. Create a kind cluster
2. Attach it to a workspace
3. Delete the kind cluster
4. Watch the logs fly

**Alternatively**
1. Create a kind cluster
2. Attach it to a workspace
3. Update the SA in the cluster so the credentials in the workloadcluster resource are invalid
4. Watch the logs fly

**Expected behavior**
Ready should be set once, and other conditions should explain the details of various checks each controller has performed.

### PR DESCRIPTION
**Pull request by csams**
Give each controller its own condition and make heartbeat manager responsible for setting `Ready` by accounting for all conditions via `conditions.SetSummary`

Update the namespace scheduler to depend on total readiness.

Fixes #865

### CODE REVIEW

**Comment by marun** [comment]
I'm still unsure that this is a desirable change given that only the heartbeat controller will be setting the ready condition in the immediate future. And unless we have a concrete plan to implement one or more controllers that would be competing with the heartbeat controller for managing the ready status of workload clusters, I'd suggest YAGNI.

File: pkg/apis/workload/v1alpha1/types.go [hunk 1]
```diff
@@ -105,8 +105,14 @@ type WorkloadClusterList struct {
...
 const (
-	// WorkloadClusterReadyCondition means the WorkloadCluster is available.
-	WorkloadClusterReadyCondition conditionsv1alpha1.ConditionType = "Ready"
+	// SyncerReady means the syncer is ready to transfer resources between KCP and the WorkloadCluster.
+	SyncerReady conditionsv1alpha1.ConditionType = "SyncerReady"
+
+	// APIImporterReady means the APIImport component is ready to import APIs from the WorkloadCluster.
+	APIImporterReady conditionsv1alpha1.ConditionType = "APIImporterReady"
+
+	// HeartbeatHealthy means the HeartbeatManager is able to contact the WorkloadCluster at a specified internval.
```
Comment (ncdc) [inline pkg/apis/workload/v1alpha1/types.go:114]:
```suggestion
	// HeartbeatHealthy means the HeartbeatManager has seen a heartbeat for the WorkloadCluster within the expected interval.
```

Trying to future-proof for when push mode is gone

File: pkg/reconciler/workload/heartbeat/heartbeat_manager.go [hunk 2]
```diff
@@ -36,27 +36,37 @@ type clusterManager struct {
 }
 
 func (c *clusterManager) Reconcile(ctx context.Context, cluster *workloadv1alpha1.WorkloadCluster) error {
+
```
Comment (ncdc) [inline pkg/reconciler/workload/heartbeat/heartbeat_manager.go:39]:
```suggestion
```

File: pkg/reconciler/workload/heartbeat/heartbeat_manager.go [hunk 3]
```diff
@@ -24,7 +24,7 @@ import (
 
 	workloadv1alpha1 "github.com/kcp-dev/kcp/pkg/apis/workload/v1alpha1"
 	"github.com/kcp-dev/kcp/pkg/reconciler/workload/basecontroller"
-	conditionsv1alpha1 "github.com/kcp-dev/kcp/third_party/conditions/apis/conditions/v1alpha1"
+	conditionsapi "github.com/kcp-dev/kcp/third_party/conditions/apis/conditions/v1alpha1"
```
Comment (ncdc) [inline pkg/reconciler/workload/heartbeat/heartbeat_manager.go:27]: Not super important, but curious why the change here?

File: pkg/reconciler/workload/heartbeat/heartbeat_manager.go [hunk 4]
```diff
@@ -36,27 +36,37 @@ type clusterManager struct {
...
+		),
+	)
+
 	latestHeartbeat := time.Time{}
 	if cluster.Status.LastSyncerHeartbeatTime != nil {
 		latestHeartbeat = cluster.Status.LastSyncerHeartbeatTime.Time
 	}
 	if latestHeartbeat.IsZero() {
-		klog.V(5).Infof("Marking WorkloadCluster %s|%s not ready due to no heartbeat", cluster.ClusterName, cluster.Name)
+		klog.V(5).Infof("Marking Syncer %s|%s not ready due to no heartbeat", cluster.ClusterName, cluster.Name)
```
Comment (ncdc) [inline pkg/reconciler/workload/heartbeat/heartbeat_manager.go:54]: Maybe change the log message here so instead of talking about marking not ready, we say we're setting HeartbeathHealthy to false b/c no heartbeat?

File: pkg/reconciler/workload/heartbeat/heartbeat_manager.go [hunk 5]
```diff
@@ -36,27 +36,37 @@ type clusterManager struct {
...
 		conditions.MarkFalse(cluster,
-			workloadv1alpha1.WorkloadClusterReadyCondition,
+			workloadv1alpha1.HeartbeatHealthy,
 			workloadv1alpha1.ErrorHeartbeatMissedReason,
-			conditionsv1alpha1.ConditionSeverityWarning,
+			conditionsapi.ConditionSeverityWarning,
 			"No heartbeat yet seen")
 	} else if time.Since(latestHeartbeat) > c.heartbeatThreshold {
-		klog.V(5).Infof("Marking WorkloadCluster %s|%s not ready due to a stale heartbeat", cluster.ClusterName, cluster.Name)
+		klog.V(5).Infof("Marking Syncer %s|%s not ready due to a stale heartbeat", cluster.ClusterName, cluster.Name)
```
Comment (ncdc) [inline pkg/reconciler/workload/heartbeat/heartbeat_manager.go:61]: Ditto

File: pkg/reconciler/workload/heartbeat/heartbeat_manager.go [hunk 6]
```diff
@@ -36,27 +36,37 @@ type clusterManager struct {
...
-			workloadv1alpha1.WorkloadClusterReadyCondition,
+			workloadv1alpha1.HeartbeatHealthy,
 			workloadv1alpha1.ErrorHeartbeatMissedReason,
-			conditionsv1alpha1.ConditionSeverityWarning,
+			conditionsapi.ConditionSeverityWarning,
 			"No heartbeat since %s", latestHeartbeat)
 	} else {
-		klog.V(5).Infof("Marking WorkloadCluster %s|%s ready", cluster.ClusterName, cluster.Name)
-		conditions.MarkTrue(cluster, workloadv1alpha1.WorkloadClusterReadyCondition)
+		klog.V(5).Infof("Marking Heartbeat healthy for %s|%s", cluster.ClusterName, cluster.Name)
```
Comment (ncdc) [inline pkg/reconciler/workload/heartbeat/heartbeat_manager.go:68]:
```suggestion
		klog.V(5).Infof("Marking Heartbeat healthy for WorkloadCluster %s|%s", cluster.ClusterName, cluster.Name)
```

File: pkg/reconciler/workload/syncer/pushmanager.go [hunk 7]
```diff
@@ -91,7 +91,6 @@ func (m *pushSyncerManager) update(ctx context.Context, cluster *workloadv1alpha
 	}
 
 	klog.Infof("Started push mode syncer from clusterName %s for pcluster %s", kcpClusterName, cluster.Name)
-	conditions.MarkTrue(cluster, workloadv1alpha1.WorkloadClusterReadyCondition)
```
Comment (ncdc) [inline pkg/reconciler/workload/syncer/pushmanager.go:94]: We don't need SyncerReady=True here?

Comment (csams) [reply pkg/reconciler/workload/syncer/pushmanager.go:94]: Yep, not sure why I removed it. `checkHealth` doesn't get called in the func that calls update if an update was needed.

File: pkg/reconciler/workload/heartbeat/heartbeat_manager.go (hunk 3 above)
Comment (csams) [reply pkg/reconciler/workload/heartbeat/heartbeat_manager.go:27]: The `conditions` library uses `conditionsapi` as the conventional import name. I'd been spelunking in the lib and was going for consistency with it. I now see `conditionsv1alpha1` is used in KCP, though, so I'll switch to that.

Comment (ncdc) [reply pkg/reconciler/workload/heartbeat/heartbeat_manager.go:27]: I think we have a mix here & there. Either is fine for now.

**Review by ncdc — APPROVED** [review]

**Comment by ncdc** [comment]
@marun @imjasonh how does this look to you?

For background/additional context: the conditions library we're using (from Cluster API) went through extensive R&D, settling on the use of SetSummary to summarize a resource's Ready condition. It's a good practice to follow, and even if we only currently have a single condition that represents Ready, for future-proofing, we should choose a unique name for that condition, and have it flow into Ready via SetSummary.

**Review by imjasonh — APPROVED** [review]
This looks like a good change, thanks! 👍
