### PR TITLE
:sparkles: Add garbage collector controller

### LINKED ISSUE #191: Cascading deletion not working - need to enable the garbage collection controller
**Describe the bug**
I'm experimenting with [camel-k](https://camel.apache.org/camel-k/latest/index.html) to get it working with KCP as a Kubernetes control plane and I noticed that as opposite as when running on a "classic" Kubernetes cluster, when a camel-k custom resource is deleted, the related CRs and standard Kubernetes created by the camel-k operator are not automatically delete. 

As example, following a creation of a `KameletBinding` CR, the camel-k operator creates the following resources and Kubernetes objects all linked by using owner references:

- `Integration`
- `Secret`
- `ConfigMap`
- `Deployment`

But when the `KameletBinding` is gets deleted, the other CRs and standard Kubernetes are not deleted.

**Expected behavior**
When cascading deletion is used, KCP should delete the object's dependents automatically.

### PR DESCRIPTION
**Pull request by astefanutti**
## Summary

This PR enables the garbage collector controller per workspace.

Requires kcp-dev/kubernetes#108.

## Related issue(s)

Fixes #191

### CODE REVIEW

File: pkg/informer/delegating_event_handler.go [hunk 1]
```diff
@@ -121,3 +123,19 @@ func (d *delegatingEventHandler) getEventHandler(resource schema.GroupResource,
 
 	return groupResourceHandlers[clusterName]
 }
+
+func clusterNameForObj(obj interface{}) logicalcluster.Name {
```
Comment (nrb) [inline pkg/informer/delegating_event_handler.go:127]: Could this function be replaced with called to https://github.com/kcp-dev/logicalcluster/blob/main/name.go#L93?

Comment (astefanutti) [reply pkg/informer/delegating_event_handler.go:127]: I think in some particular cases, like offline deletion, the object is a `cache.DeletedFinalStateUnknown`, in which case the `logicalcluster.Name` function cannot be called.

Comment (nrb) [reply pkg/informer/delegating_event_handler.go:127]: Got it, thanks!

**Comment by ncdc** [comment]
@astefanutti would love to see this run through the full test suite in CI. To do that, you can make a temporary commit (we'll drop it later) that points to your fork of Kubernetes:

```shell
GITHUB_USER=astefanutti BRANCH=pr-gc hack/bump-k8s.sh
```

File: pkg/projection/projected_apis.go [hunk 2]
```diff
@@ -37,3 +37,12 @@ func Includes(gvr schema.GroupVersionResource) bool {
 	_, exists := projectedAPIs[gvr]
 	return exists
 }
+
+// ProjectedAPIs returns the set of GVR for projected APIs.
```
Comment (ncdc) [inline pkg/projection/projected_apis.go:41]:
```suggestion
// ProjectedAPIs returns the set of GVRs for projected APIs.
```

File: pkg/projection/projected_apis.go [hunk 3]
```diff
@@ -37,3 +37,12 @@ func Includes(gvr schema.GroupVersionResource) bool {
...
+func ProjectedAPIs() (ret map[schema.GroupVersionResource]struct{}) {
```
Comment (ncdc) [inline pkg/projection/projected_apis.go:42]:
```suggestion
func ProjectedAPIs() map[schema.GroupVersionResource]struct{} {
```

**Comment by astefanutti** [comment]
@ncdc sure, just added tmp commit 93354a0c77d9d9dc6ba8a7ac01daa985050d5265.

File: pkg/reconciler/garbagecollector/garbagecollector_controller.go [hunk 4]
```diff
@@ -0,0 +1,319 @@
...
+
+	ignoredResources := make(map[schema.GroupResource]struct{})
+	// Add default ignored resources
+	for gr := range garbagecollector.DefaultIgnoredResources() {
+		ignoredResources[gr] = struct{}{}
+	}
+	// Add projected API resources
+	for gvr := range projection.ProjectedAPIs() {
+		ignoredResources[gvr.GroupResource()] = struct{}{}
+	}
```
Comment (ncdc) [inline pkg/reconciler/garbagecollector/garbagecollector_controller.go:262]: Could maybe calculate these once and store them as a field on `Controller`? I don't think they change per workspace?

File: pkg/reconciler/kubequota/kubequota_controller.go [hunk 5]
```diff
@@ -286,7 +270,7 @@ func (c *Controller) startQuotaForClusterWorkspace(ctx context.Context, clusterN
 		ReplenishmentResyncPeriod: func() time.Duration {
 			return c.fullResyncPeriod
 		},
-		DiscoveryFunc:        c.dynamicDiscoverySharedInformerFactory.DiscoveryData,
+		DiscoveryFunc:        c.dynamicDiscoverySharedInformerFactory.ServerPreferredNamespacedResources,
```
Comment (ncdc) [inline pkg/reconciler/kubequota/kubequota_controller.go:273]: Needs to be ServerPreferredResources because we support quota of cluster-scoped too

File: pkg/reconciler/kubequota/kubequota_controller.go [hunk 6]
```diff
@@ -328,7 +312,7 @@ func (c *Controller) startQuotaForClusterWorkspace(ctx context.Context, clusterN
 				logger.V(4).Info("got API change notification")
 
 				ctx, discoveryCancel = context.WithCancel(ctx)
-				resourceQuotaController.UpdateMonitors(ctx, c.dynamicDiscoverySharedInformerFactory.DiscoveryData)
+				resourceQuotaController.UpdateMonitors(ctx, c.dynamicDiscoverySharedInformerFactory.ServerPreferredNamespacedResources)
```
Comment (ncdc) [inline pkg/reconciler/kubequota/kubequota_controller.go:315]: Needs to be ServerPreferredResources because we support quota of cluster-scoped too

File: test/e2e/garbagecollector/garbagecollector_test.go [hunk 7]
```diff
@@ -0,0 +1,478 @@
...
+	orgClusterName := framework.NewOrganizationFixture(t, server)
+
+	ws := framework.NewWorkspaceFixture(t, server, orgClusterName, framework.WithName("gc-%d", 1))
+
+	t.Logf("Creating owner configmap")
+	owner, err := kubeClusterClient.CoreV1().ConfigMaps("default").
+		Apply(logicalcluster.WithCluster(ctx, ws),
+			corev1ac.ConfigMap("owner", "default"),
+			metav1.ApplyOptions{FieldManager: "e2e-test-runner"})
+	require.NoError(t, err, "Error applying owner configmap %s|default/owner: %v", ws, err)
```
Comment (ncdc) [inline test/e2e/garbagecollector/garbagecollector_test.go:80]: Global comment: don't need to include `%v` (`err`) because it's already part of `require.NoError(t, err`

File: test/e2e/garbagecollector/garbagecollector_test.go [hunk 8]
```diff
@@ -0,0 +1,478 @@
...
+	t.Parallel()
+
+	server := framework.SharedKcpServer(t)
+
+	ctx, cancel := context.WithCancel(context.Background())
+	t.Cleanup(cancel)
+
+	orgClusterName := framework.NewOrganizationFixture(t, server)
+
+	apiProviderClusterName := framework.NewWorkspaceFixture(t, server, orgClusterName)
```
Comment (ncdc) [inline test/e2e/garbagecollector/garbagecollector_test.go:116]: Global comment: add `framework.WithName(...)` as the last param to name each child workspace when calling `framework.NewWorkspaceFixture`

File: pkg/reconciler/garbagecollector/garbagecollector_controller.go (hunk 4 above)
Comment (astefanutti) [reply pkg/reconciler/garbagecollector/garbagecollector_controller.go]: Done with 5d46adb24a14aa0b2477f7234472294a3c12db6d.

File: pkg/reconciler/kubequota/kubequota_controller.go (hunk 6 above)
Comment (astefanutti) [reply pkg/reconciler/kubequota/kubequota_controller.go]: Done with fd037fb2723512a41e381cc80829722cdc9d59d8.

File: pkg/reconciler/kubequota/kubequota_controller.go (hunk 5 above)
Comment (astefanutti) [reply pkg/reconciler/kubequota/kubequota_controller.go]: Done with fd037fb2723512a41e381cc80829722cdc9d59d8.

File: pkg/indexers/indexers.go [hunk 9]
```diff
@@ -97,15 +98,55 @@ func IndexBySyncerFinalizerKey(obj interface{}) ([]string, error) {
 
 // ByIndex returns all instances of T that match indexValue in indexName in indexer.
 func ByIndex[T runtime.Object](indexer cache.Indexer, indexName, indexValue string) ([]T, error) {
+	return byIndex[T](indexer, indexName, indexValue)
+}
+
+// ListByIndex returns instances of T that match indexValue in indexName in indexer and the provided labels selector.
+func ListByIndex[T runtime.Object](indexer cache.Indexer, indexName, indexValue string, selector labels.Selector) ([]T, error) {
```
[the remark this answers is not in the document]
Comment (astefanutti) [reply pkg/indexers/indexers.go]: Good idea, done with bda61e8dc152990aec964c28fefb470bbb03f1f9.

File: pkg/informer/dynamic_discovery_shared_informer_factory.go [hunk 10]
```diff
@@ -508,25 +527,56 @@ func (d *DynamicDiscoverySharedInformerFactory) updateInformers() {
...
+				Group:        gvr.Group,
+				Version:      gvr.Version,
+				Kind:         spec.Names.Kind,
+				SingularName: spec.Names.Singular,
+				Namespaced:   spec.Scope == apiextensionsv1.NamespaceScoped,
+				// Everything we're informing on supports these
+				Verbs: []string{"create", "list", "watch", "delete"},
+			}
+		} else {
+			obj, err := d.crdIndexer.ByIndex(byGroupFirstFoundVersionResourceIndex, fmt.Sprintf("%s/%s/%s", gvr.Group, gvr.Version, gvr.Resource))
```
[the remark this answers is not in the document]
Comment (astefanutti) [reply pkg/informer/dynamic_discovery_shared_informer_factory.go]: Done with 34af461665ef4074567fa51f734014e74d03b495.

File: test/e2e/garbagecollector/garbagecollector_test.go (hunk 8 above)
Comment (astefanutti) [reply test/e2e/garbagecollector/garbagecollector_test.go]: Done with 76d0270e4a684995d52a07567734f82aa72b9af7.

File: pkg/informer/informer.go [hunk 11]
```diff
@@ -194,6 +176,32 @@ func NewDynamicDiscoverySharedInformerFactory(
...
+	}
+
+	if firstServedVersion == "" {
+		return []string{}, nil
+	}
+
+	group := crd.Spec.Group
+	resource := crd.Spec.Names.Plural
+
+	indexValue := fmt.Sprintf("%s/%s/%s", group, firstServedVersion, resource)
```
Comment (stevekuznetsov) [inline pkg/informer/informer.go:201]: We've found a lot of benefit to breaking out these index formatting functions so that users who want to query the index can ensure they're doing the right thing.

File: pkg/informer/informer.go [hunk 12]
```diff
@@ -532,25 +552,52 @@ func (d *DynamicDiscoverySharedInformerFactory) updateInformers() {
...
-
 }
 
 // gvrsToDiscoveryData returns "fake"/simulated discovery data for all the resources covered by the factory. It only
 // includes enough data in each APIResource to support what kcp currently needs (scheduling, placement, quota).
-func gvrsToDiscoveryData(gvrs map[schema.GroupVersionResource]struct{}) []*metav1.APIResourceList {
+func (d *DynamicDiscoverySharedInformerFactory) gvrsToDiscoveryData(gvrs map[schema.GroupVersionResource]struct{}) []*metav1.APIResourceList {
 	var discoveryData []*metav1.APIResourceList
 	gvResources := make(map[schema.GroupVersion][]metav1.APIResource)
+	builtInTypes := builtInInformableTypes()
```
Comment (stevekuznetsov) [inline pkg/informer/informer.go:562]: We calculate the `gvrs` parameter from this before passing it into `gvrsToDiscoveryData` - why do we end up calling this again inside?

File: pkg/informer/informer.go [hunk 13]
```diff
@@ -412,35 +420,47 @@ func gvrFor(group, version, resource string) schema.GroupVersionResource {
...
-		gvrFor("rbac.authorization.k8s.io", "v1", "roles"):                              {},
-		gvrFor("rbac.authorization.k8s.io", "v1", "rolebindings"):                       {},
-		gvrFor("events.k8s.io", "v1", "events"):                                         {},
-		gvrFor("admissionregistration.k8s.io", "v1", "mutatingwebhookconfigurations"):   {},
-		gvrFor("admissionregistration.k8s.io", "v1", "validatingwebhookconfigurations"): {},
-		gvrFor("apiextensions.k8s.io", "v1", "customresourcedefinitions"):               {},
-	}
-
-	return latest
+	return map[schema.GroupVersionResource]apiextensionsv1.CustomResourceDefinitionSpec{
```
Comment (stevekuznetsov) [inline pkg/informer/informer.go:435]: Using a struct (`apiextensionsv1.CustomResourceDefinitionSpec`) that supports many fields, but only ever setting a few of them, seems tricky for follow-up authors to remember & reason about. Why not some super-set type on GVR

```go
type GVRWithExtraInfo {
    schema.GroupVersionResource
    Kind, Singular string
    Scope
}
```

Then you can keep the previous factoring as well

File: pkg/informer/informer.go [hunk 14]
```diff
@@ -532,25 +552,52 @@ func (d *DynamicDiscoverySharedInformerFactory) updateInformers() {
 			klog.V(4).InfoS("Unable to notify discovery subscriber - channel full", "id", id)
 		}
 	}
-
 }
 
 // gvrsToDiscoveryData returns "fake"/simulated discovery data for all the resources covered by the factory. It only
 // includes enough data in each APIResource to support what kcp currently needs (scheduling, placement, quota).
-func gvrsToDiscoveryData(gvrs map[schema.GroupVersionResource]struct{}) []*metav1.APIResourceList {
+func (d *DynamicDiscoverySharedInformerFactory) gvrsToDiscoveryData(gvrs map[schema.GroupVersionResource]struct{}) []*metav1.APIResourceList {
```
Comment (stevekuznetsov) [inline pkg/informer/informer.go:559]: A factoring that keeps this as a function, not a method, might bring clarity to the overall flow here. Gather data first, pass it in here to process. Easier to test, to boot.

File: pkg/informer/informer.go [hunk 15]
```diff
@@ -645,3 +679,142 @@ func (d *DynamicDiscoverySharedInformerFactory) Unsubscribe(id string) {
...
+func (d *DynamicDiscoverySharedInformerFactory) ServerGroupsAndResources() ([]*metav1.APIGroup, []*metav1.APIResourceList, error) {
+	d.informersLock.RLock()
+	defer d.informersLock.RUnlock()
+
+	retGroups := make([]*metav1.APIGroup, len(d.discoveryData))
+	failedGroups := make(map[schema.GroupVersion]error)
+	retResourceList := make([]*metav1.APIResourceList, len(d.discoveryData))
+
+	for i, apiResourceList := range d.discoveryData {
+		gv, err := schema.ParseGroupVersion(apiResourceList.GroupVersion)
```
Comment (stevekuznetsov) [inline pkg/informer/informer.go:747]: Why do we do this parsing & transformation when fulfilling a discovery request, as opposed to filling our in-memory cache (`d.discoveryData`) with the data we're going to need to serve and making the per-request work `O(1)`?

File: pkg/informer/informer.go [hunk 16]
```diff
@@ -571,19 +618,6 @@ func gvrsToDiscoveryData(gvrs map[schema.GroupVersionResource]struct{}) []*metav
 	return discoveryData
 }
 
-// DiscoveryData implements resourcequota.NamespacedResourcesFunc and is intended to be used by the quota subsystem.
-func (d *DynamicDiscoverySharedInformerFactory) DiscoveryData() ([]*metav1.APIResourceList, error) {
```
Comment (stevekuznetsov) [inline pkg/informer/informer.go:575]: What happened to this?

File: pkg/reconciler/garbagecollector/garbagecollector_controller.go [hunk 17]
```diff
@@ -0,0 +1,319 @@
...
+		metadataClient:                        metadataClient,
+		informersStarted:                      informersStarted,
+
+		workersPerLogicalCluster: workersPerLogicalCluster,
+
+		cancelFuncs: map[logicalcluster.Name]func(){},
+
+		ignoredResources: defaultIgnoredResources(),
+
+		getClusterWorkspace: func(key string) (*tenancyv1alpha1.ClusterWorkspace, error) {
```
Comment (stevekuznetsov) [inline pkg/reconciler/garbagecollector/garbagecollector_controller.go:102]: Let's make this accept `(cluster logicalcluster.Name, name string)` please!

File: pkg/reconciler/garbagecollector/garbagecollector_controller.go [hunk 18]
```diff
@@ -0,0 +1,319 @@
...
+			return clusterWorkspacesInformer.Lister().Get(key)
+		},
+
+		listCRDs: func() ([]*apiextensionsv1.CustomResourceDefinition, error) {
```
Comment (stevekuznetsov) [inline pkg/reconciler/garbagecollector/garbagecollector_controller.go:106]: Doesn't this need a logical cluster to list in?

File: pkg/reconciler/garbagecollector/garbagecollector_controller.go [hunk 19]
```diff
@@ -0,0 +1,319 @@
...
+	_, found := c.cancelFuncs[clusterName]
+	if found {
+		logger.V(4).Info("garbage collector controller already exists")
+		return nil
+	}
+
+	logger.V(2).Info("starting garbage collector controller")
+
+	ctx, cancel := context.WithCancel(ctx)
+	ctx = klog.NewContext(ctx, logger)
```
Comment (stevekuznetsov) [inline pkg/reconciler/garbagecollector/garbagecollector_controller.go:248]: Per-controller logger - amazing!

File: pkg/reconciler/garbagecollector/garbagecollector_controller.go [hunk 20]
```diff
@@ -0,0 +1,319 @@
...
+	logger := klog.FromContext(ctx)
+
+	kubeClient := c.kubeClusterClient.Cluster(clusterName)
+
+	garbageCollector, err := garbagecollector.NewClusterAwareGarbageCollector(
+		kubeClient,
+		c.metadataClient.Cluster(clusterName),
+		restmapper.NewDeferredDiscoveryRESTMapper(memory.NewMemCacheClient(c.dynamicDiscoverySharedInformerFactory)),
+		c.ignoredResources,
+		c.dynamicDiscoverySharedInformerFactory.Cluster(clusterName),
```
Comment (stevekuznetsov) [inline pkg/reconciler/garbagecollector/garbagecollector_controller.go:269]: Nice and easy :sunglasses:

File: pkg/server/controllers.go [hunk 21]
```diff
@@ -1238,6 +1239,52 @@ func (s *Server) installReplicationController(ctx context.Context, config *rest.
...
+	if err != nil {
+		return err
+	}
+
+	metadataClient, err := kcpmetadata.NewForConfig(config)
+	if err != nil {
+		return err
+	}
+
+	// TODO: make it configurable
```
Comment (stevekuznetsov) [inline pkg/server/controllers.go:1256]: Do we want to bubble this up through options in this PR?

**Review by stevekuznetsov — COMMENTED** [review]
This looks awesome! Thanks for doing that rebase.

File: pkg/indexers/indexers.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (astefanutti) [reply pkg/indexers/indexers.go]: Made obsolete by #2104 after rebase.

File: pkg/informer/dynamic_discovery_shared_informer_factory.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (astefanutti) [reply pkg/informer/dynamic_discovery_shared_informer_factory.go]: Done.

File: test/e2e/garbagecollector/garbagecollector_test.go (hunk 7 above)
Comment (astefanutti) [reply test/e2e/garbagecollector/garbagecollector_test.go]: Done.

File: pkg/projection/projected_apis.go (hunk 2 above)
Comment (astefanutti) [reply pkg/projection/projected_apis.go]: Done.

File: pkg/projection/projected_apis.go (hunk 3 above)
Comment (astefanutti) [reply pkg/projection/projected_apis.go]: Done.

File: pkg/informer/informer.go (hunk 16 above)
Comment (astefanutti) [reply pkg/informer/informer.go:575]: `DynamicDiscoverySharedInformerFactory` now implements (most of) `discovery.DiscoveryInterface`, so this ad-hoc method has been superseded by this interface methods.

File: pkg/informer/dynamic_discovery_shared_informer_factory.go [hunk 22]
```diff
@@ -621,3 +658,142 @@ func (d *DynamicDiscoverySharedInformerFactory) Unsubscribe(id string) {
...
+	d.informersLock.RLock()
+	defer d.informersLock.RUnlock()
+
+	for _, apiResourceList := range d.discoveryData {
+		if apiResourceList.GroupVersion == groupVersion {
+			return apiResourceList.DeepCopy(), nil
+		}
+	}
+
+	// ignore 403 or 404 error to be compatible with a v1.0 server.
```
[the remark this answers is not in the document]
Comment (astefanutti) [reply pkg/informer/dynamic_discovery_shared_informer_factory.go]: It's taken from https://github.com/kubernetes/client-go/blob/ef8a2e5227798313bd86c3ab7826927bcf1cc3ee/discovery/discovery_client.go#L206-L212. I've been prudent, but I'm not sure this is still relevant, nor worth applying in that context.

File: pkg/reconciler/garbagecollector/garbagecollector_controller.go (hunk 18 above)
Comment (astefanutti) [reply pkg/reconciler/garbagecollector/garbagecollector_controller.go]: It turns out this is not needed. Simply removed.

File: pkg/informer/informer.go (hunk 13 above)
Comment (astefanutti) [reply pkg/informer/informer.go]: Done 👍🏼.

File: pkg/informer/informer.go (hunk 12 above)
Comment (astefanutti) [reply pkg/informer/informer.go]: Done 👍🏼.

File: pkg/informer/dynamic_discovery_shared_informer_factory.go [hunk 23]
```diff
@@ -508,25 +527,56 @@ func (d *DynamicDiscoverySharedInformerFactory) updateInformers() {
...
+				Verbs: []string{"create", "list", "watch", "delete"},
+			}
+		} else {
+			obj, err := d.crdIndexer.ByIndex(byGroupFirstFoundVersionResourceIndex, fmt.Sprintf("%s/%s/%s", gvr.Group, gvr.Version, gvr.Resource))
+			if err != nil {
+				utilruntime.HandleError(err)
+				continue
+			}
+			if len(obj) != 1 {
+				utilruntime.HandleError(fmt.Errorf("unable to retrieve CRD - got %s", obj))
```
[the remark this answers is not in the document]
Comment (astefanutti) [reply pkg/informer/dynamic_discovery_shared_informer_factory.go]: Done 👍🏼.

**Comment by stevekuznetsov** [comment]
@astefanutti ping when this is ready for another look!

File: pkg/informer/dynamic_discovery_shared_informer_factory.go [hunk 24]
```diff
@@ -621,3 +658,142 @@ func (d *DynamicDiscoverySharedInformerFactory) Unsubscribe(id string) {
...
+
+	for i, apiResourceList := range d.discoveryData {
+		gv, err := schema.ParseGroupVersion(apiResourceList.GroupVersion)
+		if err != nil {
+			failedGroups[schema.GroupVersion{Group: apiResourceList.GroupVersion}] = err
+			continue
+		}
+		groups[i] = metav1.APIGroup{
+			Name: gv.Group,
+			Versions: []metav1.GroupVersionForDiscovery{
```
[the remark this answers is not in the document]
Comment (astefanutti) [reply pkg/informer/dynamic_discovery_shared_informer_factory.go]: it turns out it's required to include all possible versions. Otherwise owner references that point to a version other than the conflated / first served version, do not pass the coordinates check performed by the GC graph builder, as the node identity holds the wrong version, that is the conflated / first served one.

I've changed the index function in the dynamic shared informer factory to return all the versions, and completed the GC controller e2e tests to cover that case as well.

File: pkg/informer/dynamic_discovery_shared_informer_factory.go [hunk 25]
```diff
@@ -621,3 +658,142 @@ func (d *DynamicDiscoverySharedInformerFactory) Unsubscribe(id string) {
...
+
+	for i, apiResourceList := range d.discoveryData {
+		gv, err := schema.ParseGroupVersion(apiResourceList.GroupVersion)
+		if err != nil {
+			failedGroups[schema.GroupVersion{Group: apiResourceList.GroupVersion}] = err
+			continue
+		}
+		retGroups[i] = &metav1.APIGroup{
+			Name: gv.Group,
+			Versions: []metav1.GroupVersionForDiscovery{
```
[the remark this answers is not in the document]
Comment (astefanutti) [reply pkg/informer/dynamic_discovery_shared_informer_factory.go]: Answered above.

File: pkg/reconciler/garbagecollector/garbagecollector_controller.go (hunk 17 above)
Comment (astefanutti) [reply pkg/reconciler/garbagecollector/garbagecollector_controller.go]: I've removed this function in favor of adding a `clusterWorkspaceLister` field to the controller.

File: pkg/informer/informer.go (hunk 11 above)
Comment (astefanutti) [reply pkg/informer/informer.go]: Done 👍🏼.

File: pkg/informer/informer.go (hunk 15 above)
Comment (stevekuznetsov) [reply pkg/informer/informer.go:731]: Is this outstanding?

File: pkg/informer/informer.go [hunk 26]
```diff
@@ -643,3 +663,142 @@ func (d *DynamicDiscoverySharedInformerFactory) Unsubscribe(id string) {
...
+				namespacedResources.APIResources = append(namespacedResources.APIResources, resource)
+			}
+		}
+		ret[i] = namespacedResources
+	}
+
+	return ret, nil
+}
+
+func (d *DynamicDiscoverySharedInformerFactory) RESTClient() rest.Interface {
```
Comment (stevekuznetsov) [inline pkg/informer/informer.go:790]: Yikes, what is pulling this in? What interface do we need to fulfill? Can we refactor that?

File: test/e2e/garbagecollector/garbagecollector_test.go [hunk 27]
```diff
@@ -0,0 +1,642 @@
...
+	"github.com/kcp-dev/kcp/pkg/apis/third_party/conditions/util/conditions"
+	kcpclient "github.com/kcp-dev/kcp/pkg/client/clientset/versioned"
+	"github.com/kcp-dev/kcp/test/e2e/fixtures/apifixtures"
+	wildwestv1alpha1 "github.com/kcp-dev/kcp/test/e2e/fixtures/wildwest/apis/wildwest/v1alpha1"
+	wildwestclientset "github.com/kcp-dev/kcp/test/e2e/fixtures/wildwest/client/clientset/versioned"
+	"github.com/kcp-dev/kcp/test/e2e/framework"
+)
+
+func TestGarbageCollectorBuiltInCoreV1Types(t *testing.T) {
+	t.Parallel()
```
Comment (stevekuznetsov) [inline test/e2e/garbagecollector/garbagecollector_test.go:59]: You'll want `framework.Suite("control-plane")` in all of these

File: test/e2e/garbagecollector/garbagecollector_test.go [hunk 28]
```diff
@@ -0,0 +1,642 @@
...
+			require.NoError(t, err, "error creating kcp cluster client")
+
+			_, err = kcpClusterClient.ApisV1alpha1().APIBindings().Create(logicalcluster.WithCluster(c, userClusterName), binding, metav1.CreateOptions{})
+			require.NoError(t, err)
+
+			t.Logf("Wait for the binding to be ready")
+			framework.Eventually(t, func() (bool, string) {
+				binding, err := kcpClusterClient.ApisV1alpha1().APIBindings().Get(logicalcluster.WithCluster(c, userClusterName), binding.Name, metav1.GetOptions{})
+				require.NoError(t, err, "error getting binding %s", binding.Name)
+				return conditions.IsTrue(binding, apisv1alpha1.InitialBindingCompleted), fmt.Sprintf("binding not bound: %s", toYaml(binding))
```
Comment (stevekuznetsov) [inline test/e2e/garbagecollector/garbagecollector_test.go:182]: I know you just carried this forward from other tests, but let's not use `toYaml()`: https://github.com/kcp-dev/kcp/pull/2273

**Review by stevekuznetsov — COMMENTED** [review]
This is looking really good! Couple small comments

File: test/e2e/garbagecollector/garbagecollector_test.go (hunk 27 above)
Comment (astefanutti) [reply test/e2e/garbagecollector/garbagecollector_test.go:59]: Done 👍🏼.

File: pkg/informer/informer.go (hunk 26 above)
Comment (astefanutti) [reply pkg/informer/informer.go]: This was pulled because of the RESTMapper argument passed to the GC controller factory method:

```go
restmapper.NewDeferredDiscoveryRESTMapper(memory.NewMemCacheClient(c.dynamicDiscoverySharedInformerFactory))
```

Thinking through the whole calls sequence, it turns out it's possible to remove this and be completely "push-based", while the cached RESTMapper made sense for the polling approach.

I've addressed it at the same as optimising the discovery API implementation, so discovery and REST mapping methods share the same data structures.

File: pkg/informer/informer.go (hunk 15 above)
Comment (astefanutti) [reply pkg/informer/informer.go]: I've improved this at the same time I've addressed the removal of `rest.Interface`, so discovery and REST mapping methods share the same data structures.

File: pkg/informer/informer.go [hunk 29]
```diff
@@ -530,56 +568,76 @@ func (d *DynamicDiscoverySharedInformerFactory) updateInformers() {
...
 
-	ret := make([]*metav1.APIResourceList, len(d.discoveryData))
-	for i, apiResourceList := range d.discoveryData {
-		ret[i] = apiResourceList.DeepCopy()
+			ret.apiResourceList = append(ret.apiResourceList, apiResourceList)
+		}
+		apiGroup := metav1.APIGroup{
+			Name:     group,
+			Versions: versions,
+			// TODO: PreferredVersion
```
Comment (stevekuznetsov) [inline pkg/informer/informer.go:623]: TODO when? Why? What's the implication of leaving it out now?

File: pkg/informer/informer.go [hunk 30]
```diff
@@ -643,3 +701,123 @@ func (d *DynamicDiscoverySharedInformerFactory) Unsubscribe(id string) {
...
+}
+
+func newRESTMapper(fn func() (meta.RESTMapper, error)) restMapper {
+	return restMapper{
+		delegate: meta.NewLazyRESTMapperLoader(fn),
+	}
+}
+
+type restMapper struct {
+	delegate meta.RESTMapper
```
Comment (stevekuznetsov) [inline pkg/informer/informer.go:788]: Why not just embed this, to save yourself the methods?

File: pkg/informer/informer.go (hunk 29 above)
Comment (astefanutti) [reply pkg/informer/informer.go]: Added a comment with more context about it.

File: pkg/informer/informer.go (hunk 30 above)
Comment (astefanutti) [reply pkg/informer/informer.go]: Done. This is SO much better 😃!

**Review by stevekuznetsov — APPROVED** [review]
Awesome!

/lgtm
/approve
/hold

@sttts @ncdc do either of you want to do a pass? Hold is on for you.

File: pkg/server/controllers.go (hunk 21 above)
Comment (ncdc) [reply pkg/server/controllers.go:1255]: Ok not to - same as quota

**Comment by ncdc** [comment]
@astefanutti this is ready to go!!! Please update go.mod to point to the latest kcp-dev/kubernetes (just do `hack/bump-k8s.sh`) and we can merge it!
