### PR TITLE
re-enable and fix TestAPIExportAPIBindingsAccess

### LINKED ISSUE #2263: flake: TestAPIExportAPIBindingsAccess
```
--- FAIL: TestAPIExportAPIBindingsAccess (51.30s)
    kcp.go:130: shared kcp server will target configuration "/home/runner/work/kcp/kcp/.kcp/admin.kubeconfig"
    workspaces.go:191: Created organization workspace root:e2e-org-p2l7n
    workspaces.go:124: Created root:universal workspace root:e2e-org-p2l7n:workspace1
    workspaces.go:124: Created root:universal workspace root:e2e-org-p2l7n:workspace2
    virtualworkspace_test.go:359: root:e2e-org-p2l7n:workspace1: creating APIResourceSchema 1
    virtualworkspace_test.go:360: root:e2e-org-p2l7n:workspace1: creating APIExport 1
    virtualworkspace_test.go:361: root:e2e-org-p2l7n:workspace1: creating APIResourceSchema 2
    virtualworkspace_test.go:362: root:e2e-org-p2l7n:workspace1: creating APIExport 2
    virtualworkspace_test.go:363: root:e2e-org-p2l7n:workspace1: creating APIBinding referencing APIExport 1
    virtualworkspace_test.go:364: root:e2e-org-p2l7n:workspace1: creating APIBinding referencing APIExport 2
    virtualworkspace_test.go:366: root:e2e-org-p2l7n:workspace2: creating APIBinding referencing APIExport 1
    virtualworkspace_test.go:375: root:e2e-org-p2l7n:workspace2: creating APIResourceSchema 3
    virtualworkspace_test.go:376: root:e2e-org-p2l7n:workspace2: creating APIExport 3
    virtualworkspace_test.go:377: root:e2e-org-p2l7n:workspace2: creating APIBinding referencing APIExport 3
    virtualworkspace_test.go:421: Verifying APIExport root:e2e-org-p2l7n:workspace1|export1 discovery has apis.kcp.dev
    virtualworkspace_test.go:421: Verifying APIExport export1 discovery has apibindings
    virtualworkspace_test.go:422: Verifying APIExport root:e2e-org-p2l7n:workspace1|export2 discovery has apis.kcp.dev
    virtualworkspace_test.go:422: Verifying APIExport export2 discovery has apibindings
    virtualworkspace_test.go:423: Verifying APIExport root:e2e-org-p2l7n:workspace2|export3 discovery has apis.kcp.dev
    virtualworkspace_test.go:423: Verifying APIExport export3 discovery has apibindings
    virtualworkspace_test.go:446: Verifying APIExport 1 only serves APIBinding 1|1 and 2|1
    virtualworkspace_test.go:463: Verifying APIExport 2 only serves APIBinding 2
    virtualworkspace_test.go:477: Updating APIExport 1 to claim APIBindings
    virtualworkspace_test.go:491: Updating APIBinding 1 to accept APIBindings claim
    virtualworkspace_test.go:516: Verifying APIExport 1 serves APIBindings 1|1, 1|2, and 2|1
    virtualworkspace_test.go:542: Verifying APIExport 2 still only serves APIBinding 2
    virtualworkspace_test.go:556: Updating APIBinding 1 to reject APIBindings claim
    virtualworkspace_test.go:573: Verifying APIExport 1 back to only serving its own bindings
    assertions.go:1691: Waiting for condition, but got: unexpected binding root:e2e-org-p2l7n:workspace1|binding2
    virtualworkspace_test.go:574: 
        	Error Trace:	util.go:298
        	            				virtualworkspace_test.go:434
        	            				virtualworkspace_test.go:574
        	Error:      	Condition never satisfied
        	Test:       	TestAPIExportAPIBindingsAccess
        	Messages:   	did not see expected bindings for root:e2e-org-p2l7n:workspace1|export1
```

/cc @ncdc

### PR DESCRIPTION
**Pull request by iakmc**
## Summary

- Updated YAML files from v1alpha1 to v1alpha2 format, including changing spec.reference.workspace.exportName to `spec.reference.export.name` for bindings, and spec.latestResourceSchemas to spec.resources for exports
- Added permissionClaims for apibindings resource to the export YAML files, which is required for the virtual workspace to serve claimed resources
- Fixed bug where the test constructed invalid URLs with duplicate /clusters/* path segments by using the correct client type
- Fixed test flow to accept permission claims before querying the virtual workspace (the virtual workspace only serves claimed resources after at least one binding accepts the claim)
- Added wait for PermissionClaimsApplied condition to avoid race conditions between the test and the controller
- Updated final verification to correctly check that after rejecting claims, only bindings pointing directly to the export remain visible

## What Type of PR Is This?
/kind flake

## Related Issue(s)

Fixes #2263

## Release Notes

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/virtual/apiexport/virtualworkspace_test.go [hunk 1]
```diff
@@ -393,73 +393,77 @@ func TestAPIExportAPIBindingsAccess(t *testing.T) {
 
 	exportURLs := make(map[string]string)
 
+	// Wait for APIExportEndpointSlices and populate exportURLs
+	for _, exportName := range []string{"export1", "export2"} {
+		export := exportName
+		wsPath := ws1Path
```
Comment (ntnn) [inline test/e2e/virtual/apiexport/virtualworkspace_test.go]: don't need to reassign these, a leftover i presume
