### PR TITLE
apibindings: check for conflicts, refactor controller

### LINKED ISSUE #796: apibinding e2e test fails if run more than once against a persistent server
The [apibinding e2e test](https://github.com/kcp-dev/kcp/blob/main/test/e2e/apibinding/apibinding_test.go) fails if run more than once against a persistent server. This is curious, since the testing appears to be isolated within test-local organizations and workspaces.

**To Reproduce**
1. Start a persistent test server in one terminal:
```
$ rm -rf .kcp && make build && ./bin/test-server 2>&1 | tee kcp.log
```
2. Run the test in another terminal (it should pass):
```
 go test -v  test/e2e/apibinding/apibinding_test.go -args --kubeconfig=$(pwd)/.kcp/admin.kubeconfig
```
3. Run the same test again. It should stall after logging something like the following:
```
  apibinding_test.go:109: Make sure "<group>" API group shows up in workspace "<workspace name>" group discovery
```

### LINKED ISSUE #842: Follow-up APIBindings:  set the storage versions in the APIBinding's status
Follow-up of #417:

Set the storage versions in the APIBinding's status correctly.

### PR DESCRIPTION
**Pull request by ncdc**
## Summary
When processing an APIBinding, check for naming conflicts with any other
bound CRDs in the same workspace.

This also pulls in an update to our Kubernetes fork to allow multiple CRDs in the system:bound-crds workspace to have naming conflicts.

## Related issue(s)

Fixes #796 
Fixes #842

### CODE REVIEW

File: pkg/reconciler/apibinding/name_conflict_checker.go [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+	apislisters "github.com/kcp-dev/kcp/pkg/client/listers/apis/v1alpha1"
+	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
+	crdlister "k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1"
+	"k8s.io/apimachinery/pkg/labels"
+	"k8s.io/apimachinery/pkg/util/sets"
+	"k8s.io/client-go/tools/clusters"
+)
+
+type nameConflictChecker struct {
+	apiBindingLister        apislisters.APIBindingLister
```
Comment (marun) [inline pkg/reconciler/apibinding/name_conflict_checker.go:31]: (No action required) Suggest providing function signatures (e.g. listAPIBinding, getAPIExport, etc) so that they can be trivially substituted in unit tests.

File: pkg/reconciler/apibinding/name_conflict_checker.go [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+	existingNames := sets.NewString()
+	existingKinds := sets.NewString()
+
+	crds, err := ncc.getBoundCRDs(clusterName)
+	if err != nil {
+		return fmt.Errorf("error checking for naming conflicts for cluster %s: error getting CRDs: %w", clusterName, err)
+	}
+
+	for _, crd := range crds {
+		existingNames.Insert(crd.Status.AcceptedNames.Plural)
```
Comment (marun) [inline pkg/reconciler/apibinding/name_conflict_checker.go:100]: (No action required) Hmm, so each of these 3 field values not only has to be unique across the same field in different crds but also across the other 2 fields in different crds?

File: pkg/reconciler/apibinding/name_conflict_checker.go [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+		existingNames.Insert(crd.Status.AcceptedNames.Singular)
+		existingNames.Insert(crd.Status.AcceptedNames.ShortNames...)
+
+		existingKinds.Insert(crd.Status.AcceptedNames.Kind)
+		existingKinds.Insert(crd.Status.AcceptedNames.ListKind)
+	}
+
+	if existingNames.Has(crd.Spec.Names.Plural) {
+		return fmt.Errorf("plural %q is already in use", crd.Spec.Names.Plural)
```
Comment (marun) [inline pkg/reconciler/apibinding/name_conflict_checker.go:109]: (No action required) Might it make sense to indicate which crd is already using the value to aid in troubleshooting? Question applies to any of the conflict messages.

File: test/e2e/apibinding/apibinding_test.go [hunk 4]
```diff
@@ -63,92 +67,123 @@ func TestAPIBinding(t *testing.T) {
...
+		require.False(t, groupExists(groups, wildwest.GroupName),
+			"should not have seen %s API group in service provider workspace %q group discovery", wildwest.GroupName, serviceProvider1Workspace)
+
+		t.Logf("Make sure %q API group shows up in consumer workspace %q group discovery", wildwest.GroupName, consumerWorkspace)
+		err = wait.PollImmediateWithContext(ctx, 100*time.Millisecond, wait.ForeverTestTimeout, func(c context.Context) (done bool, err error) {
+			groups, err := kcpClients.Cluster(consumerWorkspace).Discovery().ServerGroups()
+			if err != nil {
+				return false, fmt.Errorf("error retrieving consumer workspace %q group discovery: %w", consumerWorkspace, err)
+			}
+			if groupExists(groups, wildwest.GroupName) {
```
Comment (marun) [inline test/e2e/apibinding/apibinding_test.go:123]: (No action required) `return groupExists(groups, wildwest.GroupName), nil`

File: pkg/reconciler/apibinding/apibinding_reconcile.go [hunk 5]
```diff
@@ -290,16 +298,27 @@ func (r *workspaceAPIExportReferenceReconciler) reconcile(ctx context.Context, a
...
+			// Check for naming conflicts
+			if err := r.nameConflictChecker.checkForConflicts(crd, logicalcluster.From(apiBinding)); err != nil {
+				conditions.MarkFalse(
+					apiBinding,
+					apisv1alpha1.CRDReady,
+					apisv1alpha1.NamingConflictsReason,
+					conditionsv1alpha1.ConditionSeverityError,
+					err.Error(),
+				)
+				return reconcileStatusStop, nil // don't retry
```
Comment (marun) [inline pkg/reconciler/apibinding/apibinding_reconcile.go:317]: (No action required) I'm not sure what to make of the persistent `// don't retry` comments. I think it may be as important to not return an error to ensure the status change (`conditions.MarkFalse`) is persisted?

File: pkg/reconciler/apibinding/name_conflict_checker.go (hunk 2 above)
Comment (ncdc) [reply pkg/reconciler/apibinding/name_conflict_checker.go:100]: Yes - this is a reimplementation of the logic in https://github.com/kubernetes/kubernetes/blob/00bd91e558612de9b89b4c76c7a42121ac2835c6/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/status/naming_controller.go#L123.

File: pkg/reconciler/apibinding/name_conflict_checker.go (hunk 3 above)
Comment (sttts) [reply pkg/reconciler/apibinding/name_conflict_checker.go]: In reality these conflicts never happen in some tricky to diagnose way. Have never seen this in 8 years of kube.

File: pkg/reconciler/apibinding/apibinding_reconcile.go [hunk 6]
```diff
@@ -312,11 +331,15 @@ func (r *workspaceAPIExportReferenceReconciler) reconcile(ctx context.Context, a
 						err,
 					)
 					return reconcileStatusStop, nil // don't retry
+				case !apierrors.IsAlreadyExists(err):
+					// TODO(ncdc): Do we want to set a user-facing condition here?
+					// This case and the next have the same effect (retry). But this one could loop, whereas the default
+					// case should proceed on the next reconcile iteration.
```
Comment (sttts) [inline pkg/reconciler/apibinding/apibinding_reconcile.go]: this can only loop for some limited time, no? You do a get above. So only while stale the cache will return NotFound before and we land here.

Comment (sttts) [reply pkg/reconciler/apibinding/apibinding_reconcile.go]: In other words: retry is fine.

File: pkg/reconciler/apibinding/apibinding_reconcile.go [hunk 7]
```diff
@@ -330,48 +353,25 @@ func (r *workspaceAPIExportReferenceReconciler) reconcile(ctx context.Context, a
...
+
 		boundResources = append(boundResources, apisv1alpha1.BoundAPIResource{
 			Group:    schema.Spec.Group,
 			Resource: schema.Spec.Names.Plural,
 			Schema: apisv1alpha1.BoundAPIResourceSchema{
 				Name: schema.Name,
 				UID:  string(schema.UID),
 			},
-			StorageVersions: crd.Status.StoredVersions,
+			StorageVersions: storageVersions,
```
Comment (sttts) [inline pkg/reconciler/apibinding/apibinding_reconcile.go:287]: When we switch schema a new bound CRD is created, right? Do we carry along storage versions?

Comment (ncdc) [reply pkg/reconciler/apibinding/apibinding_reconcile.go:287]: Yes, a new bound CRD would be created. I need to merge old+new storage versions.

File: pkg/reconciler/apibinding/apibinding_reconcile.go (hunk 6 above)
Comment (ncdc) [reply pkg/reconciler/apibinding/apibinding_reconcile.go]: Old code/comment - deleted locally 😄

File: test/e2e/apibinding/apibinding_test.go [hunk 8]
```diff
@@ -20,6 +20,8 @@ import (
 	"context"
 	"embed"
 	"fmt"
+	"github.com/kcp-dev/apimachinery/pkg/logicalcluster"
+	"github.com/kcp-dev/kcp/third_party/conditions/util/conditions"
```
[the remark this answers is not in the document]
Comment (ncdc) [reply test/e2e/apibinding/apibinding_test.go]: Helpful hint - save yourself time: ignore reviewing imports - CI will catch it & I'll always fix before it's ready for merge 😄

File: pkg/reconciler/apibinding/name_conflict_checker.go (hunk 3 above)
Comment (ncdc) [reply pkg/reconciler/apibinding/name_conflict_checker.go]: Agreed, but this is different because users never have access to the bound CRDs. I will have a fix for this so it shows which APIBinding it conflicts with.

File: pkg/reconciler/apibinding/name_conflict_checker.go (hunk 1 above)
Comment (ncdc) [reply pkg/reconciler/apibinding/name_conflict_checker.go]: Am working on this 😄

File: pkg/reconciler/apibinding/apibinding_reconcile.go (hunk 5 above)
Comment (ncdc) [reply pkg/reconciler/apibinding/apibinding_reconcile.go]: Good point about an error precluding the status patching. I have adjusted the reconciler to always patch (open for discussion)

**Comment by sttts** [comment]
Let me know when this is ready to review (regarding https://github.com/kcp-dev/kcp/pull/823#issuecomment-1096846758).

**Comment by ncdc** [comment]
It's ready

File: pkg/reconciler/apis/apibinding/apibinding_controller.go [hunk 9]
```diff
@@ -69,19 +69,50 @@ func NewController(
...
+		apiBindingsLister: apiBindingInformer.Lister(),
+		listAPIBindings: func(clusterName logicalcluster.LogicalCluster) ([]*apisv1alpha1.APIBinding, error) {
+			list, err := apiBindingInformer.Lister().List(labels.Everything())
+			if err != nil {
+				return nil, err
+			}
+
+			var ret []*apisv1alpha1.APIBinding
+
+			for i := range list {
```
Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go:86]: (no action necessary) I have started adding an index by workspace elsewhere. Is that correct / necessary / sensible? These loops here definitely won't scale long-term.

Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go:86]: (no action necessary) I have started adding an index by workspace elsewhere. Is that correct / necessary / sensible? These loops here definitely won't scale long-term.

File: pkg/reconciler/apis/apibinding/apibinding_controller.go [hunk 10]
```diff
@@ -69,19 +69,50 @@ func NewController(
...
+		getAPIResourceSchema: func(clusterName logicalcluster.LogicalCluster, name string) (*apisv1alpha1.APIResourceSchema, error) {
+			return apiResourceSchemaInformer.Lister().Get(clusters.ToClusterAwareKey(clusterName, name))
+		},
 		apiResourceSchemaIndexer: apiResourceSchemaInformer.Informer().GetIndexer(),
-		crdLister:                crdInformer.Lister(),
-		crdIndexer:               crdInformer.Informer().GetIndexer(),
-		deletedCRDTracker:        newLockedStringSet(),
+
+		createCRD: func(ctx context.Context, crd *apiextensionsv1.CustomResourceDefinition) (*apiextensionsv1.CustomResourceDefinition, error) {
+			return crdClusterClient.Cluster(logicalcluster.From(crd)).ApiextensionsV1().CustomResourceDefinitions().Create(ctx, crd, metav1.CreateOptions{})
```
Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go:109]: (no action necessary) am not a fan of implicitly passing the cluster name through `metadata.clusterName` here in code. IMO it is clear to have it explicitly everywhere.

Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go:109]: (no action necessary) am not a fan of implicitly passing the cluster name through `metadata.clusterName` here in code. IMO it is clear to have it explicitly everywhere.

File: pkg/reconciler/apis/apibinding/apibinding_controller.go [hunk 11]
```diff
@@ -176,7 +212,7 @@ func (c *controller) enqueueAPIBinding(obj interface{}) {
 		return
 	}
 
-	klog.Infof("Queueing APIBinding %q", key)
+	klog.V(4).Infof("Queueing APIBinding %q", key)
```
Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go:215]: this might be worth a Slack thread and an update to the contributor guide to declare some verbosity level for different kinds of controller logging. We run in `V(2)` now by default. So `V(4)` seems to be fine, but maybe also `V(2)` might make sense for the main resource queuing in a controller.

Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go:215]: this might be worth a Slack thread and an update to the contributor guide to declare some verbosity level for different kinds of controller logging. We run in `V(2)` now by default. So `V(4)` seems to be fine, but maybe also `V(2)` might make sense for the main resource queuing in a controller.

File: pkg/reconciler/apis/apibinding/apibinding_controller.go [hunk 12]
```diff
@@ -301,9 +336,10 @@ func (c *controller) process(ctx context.Context, key string) error {
 	old := obj
 	obj = obj.DeepCopy()
 
-	if err := c.reconcile(ctx, obj); err != nil {
-		return err
-	}
+	reconcileErr := c.reconcile(ctx, obj)
+
+	// Regardless of whether reconcile returned an error or not, always try to patch status if needed. Return the
+	// reconciliation error at the end.
```
Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go:342]: (no action necessary) is this something we have to do elsewhere in other controllers too?

Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_controller.go:342]: (no action necessary) is this something we have to do elsewhere in other controllers too?

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go [hunk 13]
```diff
@@ -47,159 +42,43 @@ const (
...
-	}
-
-	boundSchemaUIDs := sets.NewString()
-	for _, boundResource := range apiBinding.Status.BoundResources {
-		boundSchemaUIDs.Insert(boundResource.Schema.UID)
-	}
-
-	return !exportedSchemaUIDs.Equal(boundSchemaUIDs)
-}
+func (c *controller) reconcileNew(ctx context.Context, apiBinding *apisv1alpha1.APIBinding) error {
```
Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go:67]: (no action necessary) am curious why you moved to this new style of method on `controller`.

Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go:67]: (no action necessary) am curious why you moved to this new style of method on `controller`.

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go [hunk 14]
```diff
@@ -237,209 +116,300 @@ func (r *workspaceAPIExportReferenceReconciler) reconcile(ctx context.Context, a
...
+			listAPIBindings:      c.listAPIBindings,
+			getAPIExport:         c.getAPIExport,
+			getAPIResourceSchema: c.getAPIResourceSchema,
+			getCRD:               c.getCRD,
+		}
+
+		if err := nameConflictChecker.checkForConflicts(crd, apiBinding); err != nil {
+			conditions.MarkFalse(
+				apiBinding,
+				apisv1alpha1.APIsBound,
```
Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go:196]: on rebind this is a little odd that we set `APIsBound` to false, no? The old schemas are still bound (I assume and hope), just the new binding failed. So maybe a slightly different condition name like `APIBindingSuccessful` or so would make it clear?

Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go:196]: on rebind this is a little odd that we set `APIsBound` to false, no? The old schemas are still bound (I assume and hope), just the new binding failed. So maybe a slightly different condition name like `APIBindingSuccessful` or so would make it clear?

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go [hunk 15]
```diff
@@ -237,209 +116,300 @@ func (r *workspaceAPIExportReferenceReconciler) reconcile(ctx context.Context, a
...
-			getAPIResourceSchema: c.getAPIResourceSchema,
-			getCRD:               c.getCRD,
-			createCRD:            c.createCRD,
-			updateCRD:            c.updateCRD,
-			deletedCRDTracker:    c.deletedCRDTracker,
-		},
+func (c *controller) reconcileBound(ctx context.Context, apiBinding *apisv1alpha1.APIBinding) error {
+	apiExportClusterName, err := getAPIExportClusterName(apiBinding)
+	if err != nil {
+		// Should never happen
```
Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go:321]: can happen if the export gets deleted by the owner, can't it? Also in the future with sharding it might fail here when the APIExport holding shard goes down.

Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go:321]: can happen if the export gets deleted by the owner, can't it? Also in the future with sharding it might fail here when the APIExport holding shard goes down.

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go [hunk 16]
```diff
@@ -237,209 +116,300 @@ func (r *workspaceAPIExportReferenceReconciler) reconcile(ctx context.Context, a
...
+			conditionsv1alpha1.ConditionSeverityError,
+			err.Error(),
+		)
+
+		return nil
 	}
 
-	var errs []error
+	if referencedAPIExportChanged(apiBinding) {
+		klog.Infof("APIBinding %s|%s needs rebinding because it now points to a different APIExport", apiBinding.ClusterName, apiBinding.Name)
```
Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go:334]: V(4) ?

Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go:334]: V(4) ?

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go (hunk 15 above)
Comment (sttts) [reply pkg/reconciler/apis/apibinding/apibinding_reconcile.go:321]: nevermind. ClusterName.

Comment (sttts) [reply pkg/reconciler/apis/apibinding/apibinding_reconcile.go:321]: nevermind. ClusterName.

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go [hunk 17]
```diff
@@ -237,209 +116,300 @@ func (r *workspaceAPIExportReferenceReconciler) reconcile(ctx context.Context, a
...
-}
+		// Return nil here so we don't retry. If/when there is an informer event for the correct APIExport, this
+		// APIBinding will automatically be requeued.
+		return nil
+	}
+	if err != nil {
+		conditions.MarkFalse(
+			apiBinding,
+			apisv1alpha1.APIExportValid,
+			"TODO",
```
Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go:361]: internal error?

Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go:361]: internal error?

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go [hunk 18]
```diff
@@ -237,209 +116,300 @@ func (r *workspaceAPIExportReferenceReconciler) reconcile(ctx context.Context, a
...
-	return c.crdLister.Get(clusters.ToClusterAwareKey(clusterName, name))
-}
+	var exportedSchemas []*apisv1alpha1.APIResourceSchema
+	for _, schemaName := range apiExport.Spec.LatestResourceSchemas {
+		apiResourceSchema, err := c.getAPIResourceSchema(apiExportClusterName, schemaName)
+		if apierrors.IsNotFound(err) {
+			conditions.MarkFalse(
+				apiBinding,
+				apisv1alpha1.APIExportValid,
+				"TODO",
```
Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go:379]: APIExportInvalidSchemas

Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go:379]: APIExportInvalidSchemas

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go [hunk 19]
```diff
@@ -237,209 +116,300 @@ func (r *workspaceAPIExportReferenceReconciler) reconcile(ctx context.Context, a
...
-}
+			// Return nil here so we don't retry. If/when there is an informer event for the correct APIExport, this
+			// APIBinding will automatically be requeued.
+			return nil
+		}
+		if err != nil {
+			conditions.MarkFalse(
+				apiBinding,
+				apisv1alpha1.APIExportValid,
+				"TODO",
```
Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go:392]: internal error

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go [hunk 20]
```diff
@@ -483,32 +453,43 @@ func crdFromAPIResourceSchema(schema *apisv1alpha1.APIResourceSchema) (*apiexten
...
-type lockedStringSet struct {
-	lock sync.RWMutex
-	s    sets.String
+func getAPIExportClusterName(apiBinding *apisv1alpha1.APIBinding) (logicalcluster.LogicalCluster, error) {
+	parent, hasParent := logicalcluster.From(apiBinding).Parent()
+	if !hasParent {
+		return logicalcluster.LogicalCluster{}, fmt.Errorf("a APIBinding in %s cannot reference a workspace", logicalcluster.From(apiBinding))
+	}
+	if apiBinding.Spec.Reference.Workspace == nil {
+		return logicalcluster.LogicalCluster{}, fmt.Errorf("APIBinding does not specify an APIExport")
```
Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go:462]: `// cannot happen due to APIBinding validation`

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go [hunk 21]
```diff
@@ -483,32 +453,43 @@ func crdFromAPIResourceSchema(schema *apisv1alpha1.APIResourceSchema) (*apiexten
...
 	}
-}
 
-func (l *lockedStringSet) Add(s string) {
-	l.lock.Lock()
-	defer l.lock.Unlock()
-	l.s.Insert(s)
-}
+	if apiBinding.Status.BoundAPIExport == nil {
+		return false
```
Comment (sttts) [inline pkg/reconciler/apis/apibinding/apibinding_reconcile.go:474]: had expected true here and below. So this means that "changed" is actually "was set + set to something else now". Might be clear to return true here and have the distinction between first-bind and rebind at the call site.

File: test/e2e/authorizer/authorizer_test.go [hunk 22]
```diff
@@ -48,6 +48,17 @@ import (
...
+		/* TODO: this test creates a clusterrole/clusterrolebinding in genericcontrolplane.LocalAdminCluster. Running
+		this test multiple times will not work in the current form because the names will collide. However, unique
+		names is not a sufficient solution, because any clusterrole/binding from a previous test run will pollute
+		the intent of the test. A possible fix would be to attempt to clean up any possible resources this test
+		intends to create in genericcontrolplane.LocalAdminCluster at the beginning of the test, or to split it
+		into parts that can run against a shared server, vs. those that truly cannot.
+		*/
+		t.Skip("Skipping until this test is updated to support multiple runs against a shared server")
+	}
+
```
Comment (sttts) [inline test/e2e/authorizer/authorizer_test.go:61]: addressed in https://github.com/kcp-dev/kcp/pull/921

File: pkg/reconciler/apis/apibinding/apibinding_controller.go (hunk 12 above)
Comment (ncdc) [reply pkg/reconciler/apis/apibinding/apibinding_controller.go:342]: I'd like to propose this as a pattern to implement (ideally in a base controller)

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go (hunk 13 above)
Comment (ncdc) [reply pkg/reconciler/apis/apibinding/apibinding_reconcile.go:67]: Mainly because the logic seemed to vary primarily based on phase (new vs binding vs bound)

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go (hunk 14 above)
Comment (ncdc) [reply pkg/reconciler/apis/apibinding/apibinding_reconcile.go:196]: Yeah, wanted to discuss this with you. Probably worth a live chat

File: pkg/reconciler/apis/apibinding/apibinding_controller.go (hunk 10 above)
Comment (ncdc) [reply pkg/reconciler/apis/apibinding/apibinding_controller.go:109]: Updated to take in clusterName in incoming commit

Comment (ncdc) [reply pkg/reconciler/apis/apibinding/apibinding_controller.go:109]: Updated to take in clusterName in incoming commit

File: pkg/reconciler/apis/apibinding/apibinding_controller.go (hunk 11 above)
Comment (ncdc) [reply pkg/reconciler/apis/apibinding/apibinding_controller.go:215]: 👍. If V(2) is the default, I'm wondering if we should instead move those 2s to just klog.Info and go with the unset (0/1) default?

Do you think the kcp admin would always want to see "Queueing xyz" for a standard deployment? Or only when running in a more verbose mode for debugging?

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go (hunk 16 above)
Comment (ncdc) [reply pkg/reconciler/apis/apibinding/apibinding_reconcile.go:334]: Going with 2 for now in incoming commit

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go (hunk 17 above)
Comment (ncdc) [reply pkg/reconciler/apis/apibinding/apibinding_reconcile.go:361]: 👍 in incoming commit

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go (hunk 18 above)
Comment (ncdc) [reply pkg/reconciler/apis/apibinding/apibinding_reconcile.go:379]: Do we want to expose this information to the user?

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go (hunk 19 above)
[the remark this answers is not in the document]
Comment (ncdc) [reply pkg/reconciler/apis/apibinding/apibinding_reconcile.go:392]: Fixed

File: test/e2e/authorizer/authorizer_test.go (hunk 22 above)
Comment (ncdc) [reply test/e2e/authorizer/authorizer_test.go:61]: Undone

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go (hunk 20 above)
Comment (ncdc) [reply pkg/reconciler/apis/apibinding/apibinding_reconcile.go:462]: Fixed

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go (hunk 18 above)
Comment (ncdc) [reply pkg/reconciler/apis/apibinding/apibinding_reconcile.go]: Went with internal error, simplified a bit

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go (hunk 21 above)
Comment (ncdc) [reply pkg/reconciler/apis/apibinding/apibinding_reconcile.go:464]: How about just removing the 2 if blocks that check Status.BoundAPIExport?

File: pkg/reconciler/apis/apibinding/apibinding_reconcile.go (hunk 18 above)
Comment (sttts) [reply pkg/reconciler/apis/apibinding/apibinding_reconcile.go]: not necessary I think

**Review by sttts — APPROVED** [review]
