### PR TITLE
Fix hotloop in placement due to bad patch

### LINKED ISSUE #1351: hotloop in placement reconciler
The patch hand-crafted in https://github.com/kcp-dev/kcp/blob/02dcb4ae2cc87e00d1e59c730a71c6df125a4a39/pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go#L91 is not always correct, leading to no-op changes and hot-looping because kcp constantly wants to remove an annotation, but it never succeeds.

### PR DESCRIPTION
**Pull request by ncdc**
## Summary
Fix hotloop in placement due to bad patch

## Related issue(s)

Fixes #1351

### CODE REVIEW

File: pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go [hunk 1]
```diff
@@ -77,18 +78,41 @@ func (r *placementReconciler) reconcile(ctx context.Context, ns *corev1.Namespac
 		return reconcileStatusStop, nil, err
 	}
 	deletePlacementAnnotation := func() (reconcileStatus, *corev1.Namespace, error) {
-		needsPatch := false
+		var deletePlacement bool
+		var deleteInternal bool
```
Comment (sttts) [inline pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go:82]: bad name. deleteNegotationWorkspaceAnnoation

Comment (ncdc) [reply pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go]: 😄 fixed

File: pkg/reconciler/scheduling/placement/placement_reconcile_scheduling_test.go [hunk 2]
```diff
@@ -88,7 +88,7 @@ func TestPlacementReconciler(t *testing.T) {
 			apibindings: map[logicalcluster.Name][]*apisv1alpha1.APIBinding{logicalcluster.New("root:org:ws"): {
 				bound(validExport(binding("kubernetes", "root:org:negotiation-workspace"))),
 			}},
-			wantPatch:           `{"metadata":{"annotations":{"scheduling.kcp.dev/placement":null}}}`,
+			wantPatch:           `{"metadata":{"annotations":null}}`,
```
Comment (sttts) [inline pkg/reconciler/scheduling/placement/placement_reconcile_scheduling_test.go:91]: 🔴  this is a blocker. We cannot deletion all annotation without uid+rv pre-conditions.

Comment (ncdc) [reply pkg/reconciler/scheduling/placement/placement_reconcile_scheduling_test.go:91]: I just had that thought. Will add

File: pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go [hunk 3]
```diff
@@ -77,18 +78,56 @@ func (r *placementReconciler) reconcile(ctx context.Context, ns *corev1.Namespac
...
+				if k == schedulingv1alpha1.PlacementAnnotationKey && deletePlacementAnnotation {
+					continue
+				}
+
+				if k == schedulingv1alpha1.InternalNegotiationWorkspaceAnnotationKey && deleteNegotationWorkspaceAnnotation {
+					continue
+				}
+
+				newAnnotations[k] = v
+			}
```
Comment (sttts) [inline pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go:113]: is this different to two deletes?

File: pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go [hunk 4]
```diff
@@ -77,18 +78,56 @@ func (r *placementReconciler) reconcile(ctx context.Context, ns *corev1.Namespac
...
+			})
+			if err != nil {
+				return reconcileStatusStop, nil, err
+			}
+			patchBytes, err := jsonpatch.CreateMergePatch(oldData, newData)
+			if err != nil {
+				return reconcileStatusStop, nil, err
+			}
+
+			if _, err := r.patchNamespace(ctx, clusterName, ns.Name, types.MergePatchType, patchBytes, metav1.PatchOptions{}); err != nil {
```
Comment (sttts) [inline pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go:130]: looks correct. But this code always hurts my eyes. 30 lines to create a patch.

File: pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go (hunk 3 above)
Comment (ncdc) [reply pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go:113]: I can simplify it. Was trying to avoid 2 deep copies

File: pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go (hunk 4 above)
Comment (stevekuznetsov) [reply pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go:130]: Better than three bug-fix commits for typos in a patch string ... generics should help us with the old/new marshalling and patch creation?
