### PR TITLE
fix: send initial-events-end bookmark for CachedResource virtual storage

### LINKED ISSUE #3871: CachedResource virtual storage does not send initial-events-end bookmark for WatchList requests
## Description

When a client sends a watch request with `sendInitialEvents=true&allowWatchBookmarks=true` (the WatchList protocol) for a resource backed by CachedResource virtual storage, the server returns all initial ADDED events but **never sends the `k8s.io/initial-events-end` BOOKMARK**.

For resources using regular CRD storage (`storage: crd: {}`), the bookmark is sent correctly after all initial events.

## Steps to Reproduce

1. Create a CachedResource for some API (e.g. `machineclasses.example.com`)
2. Configure an APIExport with virtual storage referencing the CachedResource
3. Send a watch request to the APIExport virtual workspace endpoint:
   ```
   GET /clusters/*/apis/example.com/v1alpha1/machineclasses?watch=1&sendInitialEvents=true&allowWatchBookmarks=true&resourceVersionMatch=NotOlderThan&resourceVersion=
   ```
4. Observe that all existing objects are returned as ADDED events, but no BOOKMARK with `k8s.io/initial-events-end` annotation follows

## Expected Behavior

After all initial ADDED events are delivered, the server should send:
```json
{"type":"BOOKMARK","object":{"metadata":{"annotations":{"k8s.io/initial-events-end":"true"},"resourceVersion":"..."}}}
```

This is the standard Kubernetes WatchList protocol behavior, as implemented by the storage Cacher for CRD-backed resources.

## Actual Behavior

The BOOKMARK is never sent. The watch stream continues indefinitely without signaling the end of initial events.

## Impact

The `WatchListClient` feature gate is enabled by default since client-go v0.35.0 (Kubernetes 1.35). Any operator using client-go v0.35.0+ that watches a CachedResource-backed resource will:

1. Use the WatchList protocol automatically (via the reflector)
2. Never receive the `initial-events-end` bookmark
3. Log `"event bookmark expired"` warnings every 10 seconds
4. The reflector's `lastSyncResourceVersion` is never properly initialized from the bookmark, leading to suboptimal watch resumption behavior

## Environment

- kcp version: v0.30.0
- Feature gate: `CacheAPIs=true`
- client-go: v0.35.1

### PR DESCRIPTION
**Pull request by maxpain**
## Summary

The `unwrappingWatch` in the CachedResource virtual storage never sends a BOOKMARK event with the `k8s.io/initial-events-end` annotation after replaying the initial list of cached objects. This causes clients using the WatchList feature (`sendInitialEvents=true`), which is the default since client-go v0.35.1 (Kubernetes 1.35), to log `event bookmark expired` warnings every 10 seconds.

Fixes #3871

## Changes

After registering the informer event handler, start a goroutine that waits for `handler.HasSynced()` (all initial items delivered), then sends a BOOKMARK with the `initial-events-end` annotation and the latest resource version seen during the initial list replay.

- Track the maximum `resourceVersion` via `atomic.Value` during initial event replay
- After `WaitForCacheSync`, send a BOOKMARK with `k8s.io/initial-events-end: "true"` annotation
- Only activate when `sendInitialEvents=true && allowWatchBookmarks=true`

## How to reproduce

1. Enable `CachedAPIs` feature gate
2. Create a `CachedResource` with identity secret
3. Configure an `APIExport` with `storage: virtual` referencing the `CachedResourceEndpointSlice`
4. Bind the API in a tenant workspace
5. Watch the resource using a client with WatchList enabled (default in client-go >= 0.35.1):
   ```
   kubectl get <resource> -w
   ```
6. Observe `event bookmark expired` warnings in client logs every 10 seconds

```release-note
Send initial-events-end bookmark for CachedResource virtual storage
```

### CODE REVIEW

**Comment by ntnn** [comment]
/ok-to-test
/assign @gman0 

Thanks for the PR!

**Comment by gman0** [comment]
/retest

```
+ ./hack/run-with-prometheus.sh make test-e2e
Downloading Prometheus v2.42.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 55124  100 55124    0     0   285k      0 --:--:-- --:--:-- --:--:--  286k

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by gman0** [comment]
/lgtm

Thanks!

File: pkg/virtual/replication/builder/unwrap.go [hunk 1]
```diff
@@ -422,6 +440,28 @@ func newUnwrappingWatch(
 	}
 	w.handler = handler
 
+	// Send the initial-events-end bookmark after the informer has replayed all
+	// existing items. Clients using WatchList (sendInitialEvents=true) expect a
+	// BOOKMARK with the k8s.io/initial-events-end annotation to signal that the
+	// initial state has been fully delivered.
+	if innerListOpts != nil && innerListOpts.SendInitialEvents != nil && *innerListOpts.SendInitialEvents && innerListOpts.AllowWatchBookmarks {
```
Comment (ntnn) [inline pkg/virtual/replication/builder/unwrap.go:447]:
```suggestion
    if ptr.Deref(innerListOpts.SendInitialEvents, false) && ptr.Deref(&innerListOpts.AllowWatchBookmarks, fasle) {
```

Comment (ntnn) [reply pkg/virtual/replication/builder/unwrap.go:447]: Just to make it read nicer. Otherwise lgtm, thanks for the PR!

Comment (mjudeikis) [reply pkg/virtual/replication/builder/unwrap.go:447]: please add to follow-up por. will tag to get this ball rolling

**Comment by cnvergence** [comment]
@maxpain can you add release note please? :)

File: pkg/virtual/replication/builder/unwrap.go (hunk 1 above)
Comment (ntnn) [reply pkg/virtual/replication/builder/unwrap.go:447]: @mjudeikis-bot Create a follow-up PR implementing this change.

Comment (mjudeikis) [reply pkg/virtual/replication/builder/unwrap.go:447]: @mjudeikis-bot do the needed ^ create a PR for this please

**Comment by ntnn** [comment]
/release-note Send initial-events-end bookmark for CachedResource virtual storage

**Comment by ntnn** [comment]
>  time="2026-03-03T09:03:35Z" level=warning msg="Failed, retrying in 1s ... (1/3). Error: initializing source docker://golang:1.24.13: pinging container registry registry-mirror.registry.svc.cluster.local:5001: Get \"http://registry-mirror.registry.svc.cluster.local:5001/v2/\": dial tcp 10.96.195.28:5001: connect: connection refused" 

uh oh

**Comment by maxpain** [comment]
Thanks everyone for the reviews and the release note! Is there anything else needed from my side, or just waiting for CI to pass?

**Comment by ntnn** [comment]
Just waiting for CI to pass, the docker registry pod seems to have problems but that should resolve itself soon^(tm), otherwise someone will have look^^
