### PR TITLE
🐛 Fix double identities for wildcard requests from APIExport virtual workspace

### LINKED ISSUE #2184: bug: Double identity decorations on URLs
### Describe the bug

If you are binding resources from 3rd party APIs with identityHash, sometimes you end-up with double decorations on URL. 

In example `APIExport` :
```
apiVersion: apis.kcp.dev/v1alpha1            
kind: APIExport                              
metadata:                                    
  annotations:                               
    kcp.dev/cluster: root:compute:controllers
  creationTimestamp: "2022-10-12T17:16:54Z"
  generation: 24                           
  name: faros.sh                           
spec:                                
  identity:                          
    secretRef:                       
      name: faros.sh                 
      namespace: kcp-system          
  latestResourceSchemas:             
  - today.requests.access.faros.sh   
  - today.agents.edge.faros.sh       
  - today.registrations.edge.faros.sh
  permissionClaims:          
  - group: access.faros.sh   
    resource: requests                                                            
  - group: edge.faros.sh                                                          
    resource: registrations                                                       
  - group: ""                                                                     
    resource: secrets                                                                                    
  - group: ""                                                                                            
    resource: serviceaccounts                                                                            
  - group: ""                                                                                                              
    resource: configmaps                                                                                                   
  - group: workload.kcp.dev                                                                                                
    identityHash: a2f09aebf5bc96033c19aaa1dbe2c1808542ad3ffd65b68e30fcdd3ae61c35cc                                         
    resource: synctargets           
```
`APIBinding`:
```
apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: faros.sh
spec:
  permissionClaims:
  - group: access.faros.sh
    resource: requests
    state: Accepted
  - group: edge.faros.sh
    resource: registrations
    state: Accepted
  - group: ""
    resource: serviceaccounts
    state: Accepted
  - group: ""
    resource: secrets
    state: Accepted
  - group: ""
    resource: configmaps
    state: Accepted
  - group: workload.kcp.dev
    resource: synctargets
    identityHash: ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d
    state: Accepted
  reference:
    workspace:
      exportName: faros.sh
      path: root:compute:controllers
```

And we have 2 requests from verbose level 8:
THis one we can see singple "decorations with identity"  `Path:"/apis/edge.faros.sh/v1alpha1/namespaces/default/registrations:b833587a82b737a93c56b67771d0a987b671e64b762ac5ce6614d237d8f8bb5b`
```
] startRequest(RequestDigest{RequestInfo: &request.RequestInfo{IsResourceRequest:true, Path:"/apis/edge.faros.sh/v1alpha1/namespaces/default/registrations:b833587a82b737a93c56b67771d0a987b671e64b762ac5ce6614d237d8f8bb5b", Verb:"list", APIPrefix:"apis", APIGroup:"edge.faros.sh", APIVersion:"v1alpha1", Namespace:"default", Resource:"registrations:b833587a82b737a93c56b67771d0a987b671e64b762ac5ce6614d237d8f8bb5b", Subresource:"
", Name:"", Parts:[]string{"registrations:b833587a82b737a93c56b67771d0a987b671e64b762ac5ce6614d237d8f8bb5b"}}, User: &user.DefaultInfo{Name:"system:apiserver", UID:"2fcd6aed-1c40-4a5d-963e-0ab665c7b579", Groups:[]string{"system:masters"}, Extra:map[string][]string(nil)}}) 
```

And second one we have double: `/apis/workload.kcp.dev/v1alpha1/synctargets:ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d:ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d`
```
 startRequest(RequestDigest{RequestInfo: &request.RequestInfo{IsResourceRequest:true, Path:"/apis/workload.kcp.dev/v1alpha1/synctargets:ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d:ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d", Verb:"list", APIPrefix:"apis", APIGroup:"workload.kcp.dev", APIVersion:"v1alpha1", Namespace:"", Resource:"synctargets:ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d:ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d", Subresource:"", Name:"", Parts:[]string{"synctargets:ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d:ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d"}}, User: &user.DefaultInfo{Name:"system:apiserver", UID:"2fcd6aed-1c40-4a5d-963e-0ab665c7b579", Groups:[]string{"system:masters"}, Extra:map[string][]string(nil)}})
```
This leads to 404 being returned from storage.

Existing decorations was here for a long time:
https://github.com/kcp-dev/kcp/blob/bc50273a7a1fe2f192ccf4bb4c00120d45607e7d/pkg/server/bootstrap/identity.go#L285

And we added second decorator here:
https://github.com/kcp-dev/kcp/blob/bc50273a7a1fe2f192ccf4bb4c00120d45607e7d/pkg/virtual/framework/forwardingregistry/store.go#L279 

Fix is quite simple:
```
if !strings.Contains(comps[5],":"){
    comps[5] += ":" + id
}
```

But the fact we do this in 2 locations but not all code hits `decorateWildcardPathsWithResourceIdentities`  and some hits boths. 
I didn't yet went all-in to find out how bussiness logic is constructed so this happens, but this small fix fixed beahviour for double decorations. 

### Steps To Reproduce

See description. 

### Expected Behaviour

No double decorations 

### Additional Context

https://gist.github.com/mjudeikis/39869eed948f6ab7278c0b5b7999d6a5 

:exploding_head:

### LINKED ISSUE #2308: bug: initializing workspaces vw allows access to any workspace regardless of status or initializer name
### Describe the bug

/services/initializingworkspaces/$initializerName/ allows GET/UPDATE access to individual workspaces by name. It is only supposed to expose initializing workspaces for the given $initializerName. It actually exposes all workspaces, regardless of status, and regardless of initializer name.

### Steps To Reproduce

1. Create a new ClusterWorkspaceType with spec.initializer=true
2. `k ws create foo --type $yourType`
3. When it says it's waiting for the workspace to be ready, hit ctrl-c
4. `k --user shard-admin --server https://localhost:6443 get --raw /services/initializingworkspaces/bleep:bloop/clusters/root/apis/tenancy.kcp.dev/v1alpha1/clusterworkspaces/compute`
5. ClusterWorkspace is returned

### Expected Behaviour

Get a not found error

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ncdc**
## Summary

Fix a bug where wildcard requests coming from the APIExport virtual workspace for "built-in" kcp types (e.g. ClusterWorkspaceTypes) had the identity set by the virtual workspace, then set a second time by `decorateWildcardPathsWithResourceIdentities`.

## Related issue(s)

Fixes #2184
Fixes #2308
Incorporates & supersedes #2245

### CODE REVIEW

**Comment by ncdc** [comment]
/hold
need to fix something

**Comment by sttts** [comment]
Wait.

**Comment by sttts** [comment]
No decorateWildcardPathsWithResourceIdentities client should be used to forward requests from a VW.

/hold

**Comment by ncdc** [comment]
Updated to change the VW server to use a "clean" client that doesn't inject identities. Had to reimplement similar logic in the initializing workspaces vw. PTAL. Happy to adjust as needed.

File: pkg/server/bootstrap/identity.go [hunk 1]
```diff
@@ -277,17 +277,31 @@ func decorateWildcardPathsWithResourceIdentities(urlPath string, ids *identities
 		return urlPath, nil
 	}
 
-	if strings.Contains(comps[5], ":") {
-		return urlPath, nil
+	// It's possible the incoming request already has an identity specified. Make sure we exclude that when
+	// determining the resource in question.
+	parts := strings.SplitN(comps[5], ":", 2)
+	if len(parts) == 0 {
```
Comment (sttts) [inline pkg/server/bootstrap/identity.go:283]: can this ever happen?

Comment (ncdc) [reply pkg/server/bootstrap/identity.go:283]: Probably not, but can't hurt to have the code here?

File: pkg/virtual/framework/forwardingregistry/rest.go [hunk 2]
```diff
@@ -66,35 +94,49 @@ func NewStorage(ctx context.Context, resource schema.GroupVersionResource, apiEx
...
 
-	delegate := DefaultDynamicDelegatedStoreFuncs(
+	store := DefaultDynamicDelegatedStoreFuncs(
 		factory, listFactory, destroyer,
 		strategy, tableConvertor,
 		resource, apiExportIdentityHash, categories,
 		dynamicClusterClient, []string{}, *patchConflictRetryBackoff, ctx.Done(),
 	)
-	store := wrapper(resource.GroupResource(), delegate)
+	if wrapper != nil {
```
Comment (stevekuznetsov) [inline pkg/virtual/framework/forwardingregistry/rest.go:103]: You have an inherent `nil` check in the implementation of `Decorate()` - do we need it here?

File: pkg/virtual/framework/forwardingregistry/rest_test.go [hunk 3]
```diff
@@ -110,9 +110,8 @@ func newStorage(t *testing.T, clusterClient kcpdynamic.ClusterInterface, apiExpo
 		nil,
 		clusterClient,
 		patchConflictRetryBackoff,
-		func(_ schema.GroupResource, store *forwardingregistry.StoreFuncs) *forwardingregistry.StoreFuncs {
-			return store
-		})
+		forwardingregistry.StorageWrapperFunc(func(_ schema.GroupResource, store *forwardingregistry.StoreFuncs) {
```
Comment (stevekuznetsov) [inline pkg/virtual/framework/forwardingregistry/rest_test.go:113]: You have an inherent `nil` check - can we just omit this?

File: pkg/virtual/framework/forwardingregistry/rest.go [hunk 4]
```diff
@@ -66,35 +94,49 @@ func NewStorage(ctx context.Context, resource schema.GroupVersionResource, apiEx
...
-	delegateUpdate := statusDelegate.UpdaterFunc
-	statusDelegate.UpdaterFunc = func(ctx context.Context, name string, objInfo rest.UpdatedObjectInfo, createValidation rest.ValidateObjectFunc, updateValidation rest.ValidateObjectUpdateFunc, forceAllowCreate bool, options *metav1.UpdateOptions) (runtime.Object, bool, error) {
+	delegateUpdate := statusStore.UpdaterFunc
+	statusStore.UpdaterFunc = func(ctx context.Context, name string, objInfo rest.UpdatedObjectInfo, createValidation rest.ValidateObjectFunc, updateValidation rest.ValidateObjectUpdateFunc, forceAllowCreate bool, options *metav1.UpdateOptions) (runtime.Object, bool, error) {
 		// We are explicitly setting forceAllowCreate to false in the call to the underlying storage because
 		// subresources should never allow create on update.
 		return delegateUpdate(ctx, name, objInfo, createValidation, updateValidation, false, options)
 	}
-	statusStore := wrapper(resource.GroupResource(), statusDelegate)
+	if wrapper != nil {
```
Comment (stevekuznetsov) [inline pkg/virtual/framework/forwardingregistry/rest.go:120]: You have an inherent nil check in the implementation of Decorate() - do we need it here?

File: pkg/virtual/initializingworkspaces/builder/forwarding.go [hunk 5]
```diff
@@ -42,112 +42,173 @@ import (
...
-		)
+		identities := map[schema.GroupResource]string{
+			{Group: "tenancy.kcp.dev", Resource: "clusterworkspaces"}: identity,
+		}
 
-		storage, statusStorage := registry.NewStorage(
+		return registry.ProvideReadOnlyRestStorage(
 			ctx,
-			resource,
-			"", // ClusterWorkspaces have no identity
```
Comment (stevekuznetsov) [inline pkg/virtual/initializingworkspaces/builder/forwarding.go:83]: oops

**Review by stevekuznetsov — CHANGES_REQUESTED** [review]
Some small comments, otherwise LGTM

File: pkg/virtual/framework/forwardingregistry/rest.go (hunk 4 above)
Comment (ncdc) [reply pkg/virtual/framework/forwardingregistry/rest.go:120]: I would keep it - you never know if some other implementation omits the nil check.

File: pkg/virtual/framework/forwardingregistry/rest_test.go (hunk 3 above)
Comment (ncdc) [reply pkg/virtual/framework/forwardingregistry/rest_test.go:113]: If we keep the nil check in NewStorage, yes

File: pkg/virtual/framework/forwardingregistry/rest.go (hunk 4 above)
Comment (stevekuznetsov) [reply pkg/virtual/framework/forwardingregistry/rest.go:120]: Sure thing
