### PR TITLE
✨ Check for identityHash in APIExport admission and support multiple versions for APIs in permission claims

### LINKED ISSUE #2161: bug: APIExport controller uses first encountered `GroupResource` match for internal APIs, but separate schemas exist for built-in APIs with multiple versions
### Describe the bug

`APIResourceSchema` for all built-in APIs are generated [here](https://github.com/kcp-dev/kcp/blob/525b29592b773f16f408f805a3f8b044e8e1e8a6/pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go#L293) and then [stored in a slice](https://github.com/kcp-dev/kcp/blob/525b29592b773f16f408f805a3f8b044e8e1e8a6/pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go#L302). When [evaluating whether a permission claim is for an internal API](https://github.com/kcp-dev/kcp/blob/525b29592b773f16f408f805a3f8b044e8e1e8a6/pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go#L111), we [loop through](https://github.com/kcp-dev/kcp/blob/525b29592b773f16f408f805a3f8b044e8e1e8a6/pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go#L280) the generated `APIResourceSchema` and select the [first match by group / resource](https://github.com/kcp-dev/kcp/blob/525b29592b773f16f408f805a3f8b044e8e1e8a6/pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go#L281). However, some built-in APIs (such as `FlowSchema` [`v1beta1`](https://github.com/kcp-dev/kcp/blob/525b29592b773f16f408f805a3f8b044e8e1e8a6/pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go#L444) and [`v1beta2`](https://github.com/kcp-dev/kcp/blob/525b29592b773f16f408f805a3f8b044e8e1e8a6/pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go#L466)) have multiple versions, but have a separate `APIResourceSchema` generated for each version. This means that when we loop through, we always use the schema that was added to the slice first.

### Steps To Reproduce

1. Start kcp.
2. Export `FlowSchemas`.
3. Observe that only `v1beta1` is served.

### Expected Behaviour

I believe what would be expected here is that we do match on `GroupResource`, but that the `APIResourceSchema` returned contains schemas for both versions of the given resource.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by hasheddan**
## Summary

This patch set includes two primary changes:

Update the APIResourceSchema generation to consider multiple versions of
an API and append the schemas to one ARS rather than generating a
separate ARS for each.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

Adds an APIExport admission plugin that, for the time-being, only
validates that any permissionClaims for types that are not built-in
include an identityHash.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

The first can be observed when creating an `APIExport` with `permissionClaims` on `FlowSchemas` or `PriorityLevelConfigurations`.

Before:
```
🤖 (kxp) k -s https://192.168.1.189:6443/services/apiexport/root/kxp.crossplane.io/clusters/* api-versions
apiextensions.crossplane.io/v1
apiextensions.crossplane.io/v1alpha1
flowcontrol.apiserver.k8s.io/v1beta1
pkg.crossplane.io/v1
pkg.crossplane.io/v1alpha1
pkg.crossplane.io/v1beta1
secrets.crossplane.io/v1alpha1
v1
```

After:
```
🤖 (kxp) k -s https://192.168.1.189:6443/services/apiexport/root/kxp.crossplane.io/clusters/* api-versions
apiextensions.crossplane.io/v1
apiextensions.crossplane.io/v1alpha1
flowcontrol.apiserver.k8s.io/v1beta1
flowcontrol.apiserver.k8s.io/v1beta2
pkg.crossplane.io/v1
pkg.crossplane.io/v1alpha1
pkg.crossplane.io/v1beta1
secrets.crossplane.io/v1alpha1
v1
```

The second can be observed by trying to include a `permissionClaim` for something like `Deployment` (not built-in) without an `identityHash`:
```
🤖 (kxp) cat bad-export.yaml 
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: data.my.domain
spec:
  latestResourceSchemas:
    - today.widgets.data.my.domain
  permissionClaims:
    - group: ""
      resource: "secrets"
    - group: ""
      resource: "configmaps"
    - group: ""
      resource: "namespaces"
    - group: "apps"
      resource: "deployments"
🤖 (kxp) k apply -f bad-export.yaml 
Error from server (Forbidden): error when creating "bad-export.yaml": apiexports.apis.kcp.dev "data.my.domain" is forbidden: spec.permissionClaims.[3].identityHash: Invalid value: "": identityHash is required for API types that are not built-in
```

## Related issue(s)

Fixes #2161 
xref #2152 (more work to be done on exposing conditions for other failure modes)

### CODE REVIEW

**Comment by hasheddan** [comment]
Need to cleanup some of these e2e tests that I believe are correctly failing now.

File: pkg/admission/apiexport/admission.go [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+		return fmt.Errorf("failed to convert unstructured to APIExport: %w", err)
+	}
+
+	for i, pc := range ae.Spec.PermissionClaims {
+		if pc.IdentityHash == "" && !e.isBuiltInFn(pc.GroupResource) && pc.Group != apis.GroupName {
+			return admission.NewForbidden(a,
+				field.Invalid(
+					field.NewPath("spec").
+						Child("permissionClaims").
+						Child(fmt.Sprintf("[%d]", i)).
```
Comment (ncdc) [inline pkg/admission/apiexport/admission.go:88]: You can use .Index here

File: pkg/admission/apiexport/admission_test.go [hunk 2]
```diff
@@ -0,0 +1,217 @@
...
+		apisv1alpha1.Resource(resource).WithVersion("v1alpha1"),
+		"",
+		admission.Update,
+		&metav1.UpdateOptions{},
+		false,
+		&user.DefaultInfo{},
+	)
+}
+
+func TestAdmission(t *testing.T) {
```
Comment (ncdc) [inline pkg/admission/apiexport/admission_test.go:68]: Not required but I think we can simplify the length of the test...

- Change the test case struct to something like
```go
update bool
builtIn bool
kind string
resource string
hasIdentity bool
want error
```
- Update the main t.Run logic to create an APIExport based on the testCase data, along with either a create or update attr

I think this will make it shorter if you are interested

Comment (hasheddan) [reply pkg/admission/apiexport/admission_test.go:68]: Definitely interested -- thanks for the recommendation!

Comment (hasheddan) [reply pkg/admission/apiexport/admission_test.go:67]: Updated 👍🏻

File: pkg/admission/apiexport/admission.go [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+		func(_ io.Reader) (admission.Interface, error) {
+			return NewAPIExportAdmission(builtinapiexport.IsBuiltInAPI), nil
+		})
+}
+
+// APIExportAdmission is an admission plugin for checking APIExport validity.
+type APIExportAdmission struct {
+	*admission.Handler
+
+	isBuiltInFn func(apisv1alpha1.GroupResource) bool
```
Comment (ncdc) [inline pkg/admission/apiexport/admission.go:49]: nit: I would call this `isBuiltIn`

File: pkg/admission/apiexport/admission.go [hunk 4]
```diff
@@ -0,0 +1,96 @@
...
+}
+
+// NewAPIExportAdmission constructs a new APIExportAdmission admission plugin.
+func NewAPIExportAdmission(isInternal func(apisv1alpha1.GroupResource) bool) *APIExportAdmission {
```
Comment (ncdc) [inline pkg/admission/apiexport/admission.go:53]:
```suggestion
func NewAPIExportAdmission(isBuiltIn func(apisv1alpha1.GroupResource) bool) *APIExportAdmission {
```

File: pkg/admission/apiexport/admission_test.go [hunk 5]
```diff
@@ -0,0 +1,174 @@
...
+		&metav1.CreateOptions{},
+		false,
+		&user.DefaultInfo{},
+	)
+}
+
+func updateAttr(name string, obj runtime.Object, kind, resource string) admission.Attributes {
+	return admission.NewAttributesRecord(
+		helpers.ToUnstructuredOrDie(obj),
+		nil,
```
Comment (ncdc) [inline pkg/admission/apiexport/admission_test.go:54]: Since this is an update, I know it doesn't matter for the code under test, but should we fill in the "old" object here?

File: pkg/admission/apiexport/admission_test.go [hunk 6]
```diff
@@ -0,0 +1,174 @@
...
+}
+
+func TestAdmission(t *testing.T) {
+	cases := map[string]struct {
+		attr        admission.Attributes
+		update      bool
+		kind        string
+		resource    string
+		hasIdentity bool
+		isBuiltIn   func(apisv1alpha1.GroupResource) bool
```
Comment (ncdc) [inline pkg/admission/apiexport/admission_test.go:74]: Unless you're intending to vary the return based on the input, I think this can be a normal `bool` and you can set the function pointer once, inside t.Run?

File: pkg/admission/apiexport/admission_test.go [hunk 7]
```diff
@@ -0,0 +1,174 @@
...
+		},
+		"ValidUpdateNonInternal": {
+			update:      true,
+			kind:        "APIExport",
+			resource:    "apiexports",
+			hasIdentity: true,
+			isBuiltIn: func(gr apisv1alpha1.GroupResource) bool {
+				return false
+			},
+		},
```
Comment (ncdc) [inline pkg/admission/apiexport/admission_test.go:136]: Missing test case(s) where builtIn=true

File: pkg/admission/apiexport/admission_test.go [hunk 8]
```diff
@@ -0,0 +1,174 @@
...
+			update:   true,
+			kind:     "APIExport",
+			resource: "apiexports",
+			isBuiltIn: func(gr apisv1alpha1.GroupResource) bool {
+				return false
+			},
+			want: field.Invalid(
+				field.NewPath("spec").
+					Child("permissionClaims").
+					Index(0).
```
Comment (ncdc) [inline pkg/admission/apiexport/admission_test.go:115]: Should probably add a test case that verifies a nonzero index?

File: pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go [hunk 9]
```diff
@@ -92,23 +79,25 @@ func (c *APIReconciler) reconcile(ctx context.Context, apiExport *apisv1alpha1.A
...
 		if _, found := apiResourceSchemas[gr]; found {
 			if otherClaim, found := claims[gr]; found {
 				logger.Info("permission claim is shadowed by another claim", "claim", pc, "otherClaim", otherClaim)
-			} else {
-				logger.Info("permission claim is shadowed by exported resource", "claim", pc)
+				continue
 			}
-			continue
+
+			logger.Info("permission claim is shadowed by exported resource", "claim", pc)
```
Comment (ncdc) [inline pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go:92]: Do we need a continue after this?

File: pkg/virtual/syncer/schemas/builtin/builtin_test.go [hunk 10]
```diff
@@ -0,0 +1,12 @@
+package builtin
+
+import (
+	"testing"
+
+	"github.com/stretchr/testify/require"
+	_ "k8s.io/kubernetes/pkg/apis/core/install"
```
[the remark this answers is not in the document]
Comment (ncdc) [reply pkg/virtual/syncer/schemas/builtin/builtin_test.go:24]: Sounds like we should?

[the remark this answers is not in the document]
Comment (hasheddan) [reply pkg/virtual/syncer/schemas/builtin/builtin_test.go:24]: I'm happy to, though in theory this is a change in behavior that is not strictly how all consumers would have to behave today. In practice, kcp is installing the core types into the legacy schema before this `init()` runs, but not all consumers have to. In general I don't love this pattern of registering schemas in `init()` calls, and would lean towards going ahead and moving the anonymous import (as you suggest) to cover the 99% case here.

File: pkg/admission/apiexport/admission_test.go (hunk 5 above)
Comment (hasheddan) [reply pkg/admission/apiexport/admission_test.go:54]: Happy to 👍🏻

File: pkg/virtual/syncer/schemas/builtin/builtin_test.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (ncdc) [reply pkg/virtual/syncer/schemas/builtin/builtin_test.go:24]: @sttts what do you prefer?

File: pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go (hunk 9 above)
Comment (hasheddan) [reply pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go:92]: good catch -- yes 👍🏻

File: pkg/admission/apiexport/admission_test.go (hunk 8 above)
Comment (hasheddan) [reply pkg/admission/apiexport/admission_test.go:115]: will do 👍🏻

**Comment by ncdc** [comment]
/lgtm

Would like to hear Stefan's thoughts on the import question

File: pkg/virtual/syncer/schemas/builtin/builtin_test.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (hasheddan) [reply pkg/virtual/syncer/schemas/builtin/builtin_test.go:24]: @sttts any thoughts here?

File: pkg/virtual/syncer/schemas/builtin/builtin.go [hunk 11]
```diff
@@ -0,0 +1,100 @@
...
+	"github.com/kcp-dev/kcp/pkg/virtual/framework/internalapis"
+)
+
+// syncerSchemas contains a list of internal APIs that should be exposed for the
+// syncer of any SyncTarget.
+var SyncerSchemas map[apisv1alpha1.GroupResource]*apisv1alpha1.APIResourceSchema
+
+func init() {
+	genericcontrolplane.Install(legacyscheme.Scheme)
+	schemes := []*runtime.Scheme{legacyscheme.Scheme}
```
Comment (sttts) [inline pkg/virtual/syncer/schemas/builtin/builtin.go:39]: what is this used for? don't like to see the legacyscheme in our code.

File: pkg/virtual/syncer/schemas/builtin/builtin_test.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (sttts) [reply pkg/virtual/syncer/schemas/builtin/builtin_test.go:24]: don't have much context here. But in general it is highly discourage to use the legacyscheme in any way, especially in new code like kcp. Create dedicated schemes and add the group you want via the AddToScheme methods.

File: pkg/virtual/syncer/schemas/builtin/builtin.go (hunk 11 above)
Comment (hasheddan) [reply pkg/virtual/syncer/schemas/builtin/builtin.go:39]: @sttts this isn’t strictly new in this patch set, just being relocated from the syncer API reconciler. I presume the legacy scheme is being used as the sync target is assumed to be Kubernetes API-compatible. Happy to update this to explicitly add each type in the internal API list below to the scheme.

Comment (ncdc) [reply pkg/virtual/syncer/schemas/builtin/builtin.go:39]: I would recommend doing a follow-up to deal with legacyscheme usage as a whole

Comment (hasheddan) [reply pkg/virtual/syncer/schemas/builtin/builtin.go:39]: @ncdc happy to open a tracking issue and tackle 👍🏻

**Comment by ncdc** [comment]
Approving. Keep merging & iterate on 😄 
/approve

File: pkg/virtual/syncer/schemas/builtin/builtin.go (hunk 11 above)
Comment (ncdc) [reply pkg/virtual/syncer/schemas/builtin/builtin.go:39]: @hasheddan yes let's do that please, thanks!
